// Source: Papyrus360 client roster (Indian + international)
// Lat/lon used for India outline map. Confirm flag tracks location verification.

export type Client = {
  slug: string;
  name: string;
  short: string;
  city: string;
  state: string;
  country: string;
  lat: number;
  lon: number;
  grade?: string;
  product?: string;
  testimonial?: string;
  verified: boolean;
};

export const CLIENTS: Client[] = [
  // ====== INDIA — WEST (Gujarat, Maharashtra) ======
  {
    slug: "nr-agarwal",
    name: "NR Agarwal Industries Ltd",
    short: "NR Agarwal",
    city: "Vapi",
    state: "Gujarat",
    country: "India",
    lat: 20.37,
    lon: 72.91,
    grade: "Writing & Printing, Duplex",
    verified: true,
  },
  {
    slug: "jk-paper",
    name: "JK Papers Ltd",
    short: "JK Papers",
    city: "Songadh",
    state: "Gujarat",
    country: "India",
    lat: 21.39,
    lon: 74.04,
    grade: "Packaging Board, W&P",
    product: "Netique Deckle Software",
    testimonial:
      "This is to certify that we have been using Netique Deckle Software in our Packaging Board division at Songarth Plant. The software has been performing well and our deckle utilization has improved.",
    verified: true,
  },
  {
    slug: "mehali-paper",
    name: "Mehali Papers Pvt Ltd",
    short: "Mehali Papers",
    city: "Dahej",
    state: "Gujarat",
    country: "India",
    lat: 21.70,
    lon: 72.57,
    grade: "Coated Duplex Board",
    testimonial:
      "We would like to congratulate Netique Infotech for their excellent support and service in providing Deckle Matching Software. Netique has enabled us to obtain smooth and easier combinations for maximum and effective utilization of deckles on machines. We appreciate the quality of service and support provided.",
    verified: true,
  },
  {
    slug: "lemit-papers",
    name: "Lemit Papers",
    short: "Lemit Paper",
    city: "Vapi",
    state: "Gujarat",
    country: "India",
    lat: 20.37,
    lon: 72.91,
    grade: "Kraft",
    verified: true,
  },
  {
    slug: "pinax-paper",
    name: "Pinax Paper Mills Pvt Ltd",
    short: "Pinax Paper",
    city: "Durgapur",
    state: "West Bengal",
    country: "India",
    lat: 23.55,
    lon: 87.32,
    grade: "Kraft (roll)",
    verified: true,
  },
  {
    slug: "jodhani-paper",
    name: "Jodhani Paper",
    short: "Jodhani Paper",
    city: "Surat",
    state: "Gujarat",
    country: "India",
    lat: 21.17,
    lon: 72.83,
    grade: "Kraft",
    verified: true,
  },
  {
    slug: "ambani-papers",
    name: "Ambani Papers",
    short: "Ambani Papers",
    city: "Vapi",
    state: "Gujarat",
    country: "India",
    lat: 20.37,
    lon: 72.91,
    grade: "Kraft",
    verified: true,
  },
  {
    slug: "gayatrishakti-tissue",
    name: "Gayatrishakti Tissue",
    short: "Gayatrishakti",
    city: "Vapi",
    state: "Gujarat",
    country: "India",
    lat: 20.37,
    lon: 72.91,
    grade: "Tissue",
    verified: true,
  },

  // ====== INDIA — NORTH (Punjab, UP, Uttarakhand) ======
  {
    slug: "khanna-paper",
    name: "Khanna Paper Mills (KPM)",
    short: "Khanna Paper Mills",
    city: "Amritsar",
    state: "Punjab",
    country: "India",
    lat: 31.63,
    lon: 74.87,
    grade: "Newsprint, W&P, Recycled",
    verified: true,
  },
  {
    slug: "krafton-paper",
    name: "Krafton Paper India Pvt Ltd",
    short: "Krafton Paper",
    city: "Khanna",
    state: "Punjab",
    country: "India",
    lat: 30.7,
    lon: 76.22,
    grade: "Kraft",
    verified: true,
  },
  {
    slug: "padmavati-pulp-papers",
    name: "Padmavati Pulp & Paper Mills",
    short: "Padmavati",
    city: "Ambarnath",
    state: "Maharashtra",
    country: "India",
    lat: 19.2,
    lon: 73.18,
    grade: "Recycled Kraft, Test Liner, Fluting Media",
    verified: true,
  },
  {
    slug: "saraswati-udyog",
    name: "Saraswati Udyog India Limited",
    short: "Saraswati Udyog",
    city: "Saharanpur",
    state: "Uttar Pradesh",
    country: "India",
    lat: 29.97,
    lon: 77.55,
    grade: "Kraft",
    verified: true,
  },
  {
    slug: "kailashidevi-pulp",
    name: "Kailashidevi Pulp and Paper Products",
    short: "Kailashidevi",
    city: "Muzaffarnagar",
    state: "Uttar Pradesh",
    country: "India",
    lat: 29.47,
    lon: 77.7,
    grade: "Pulp, Paper",
    verified: true,
  },
  {
    slug: "pakka",
    name: "Pakka — Packaging with a Soul",
    short: "Pakka",
    city: "Ayodhya",
    state: "Uttar Pradesh",
    country: "India",
    lat: 26.79,
    lon: 82.19,
    grade: "Moulded fibre, Bagasse",
    verified: true,
  },
  {
    slug: "kk-duplex",
    name: "K K Duplex Paper Mills",
    short: "K K Duplex",
    city: "Muzaffarnagar",
    state: "Uttar Pradesh",
    country: "India",
    lat: 29.47,
    lon: 77.7,
    grade: "Duplex Board",
    verified: false,
  },

  // ====== INDIA — SOUTH (Tamil Nadu, Andhra Pradesh) ======
  {
    slug: "sripathi-paper-boards",
    name: "Sripathi Paper & Boards P Ltd",
    short: "Sripathi",
    city: "Sivakasi",
    state: "Tamil Nadu",
    country: "India",
    lat: 9.45,
    lon: 77.79,
    grade: "W&P, Board",
    verified: true,
  },
  {
    slug: "deevya-shakti",
    name: "Deevya Shakti Papers",
    short: "Deevya Shakti",
    city: "Andhra Pradesh",
    state: "Andhra Pradesh",
    country: "India",
    lat: 16.5,
    lon: 80.65,
    grade: "Kraft",
    verified: false,
  },
  {
    slug: "sattur-sri-venkateshware",
    name: "Sattur Sri Venkateshware Duplex Boards",
    short: "Sri Venkateshware",
    city: "Sattur",
    state: "Tamil Nadu",
    country: "India",
    lat: 9.36,
    lon: 77.92,
    grade: "Duplex Board",
    verified: true,
  },
  {
    slug: "supreme-coated-board",
    name: "Supreme Coated Board Mills",
    short: "Supreme Coated",
    city: "Sivakasi",
    state: "Tamil Nadu",
    country: "India",
    lat: 9.45,
    lon: 77.79,
    grade: "Coated Board",
    verified: false,
  },
  {
    slug: "edicon",
    name: "Edicon Paper Product Pvt Ltd",
    short: "Edicon Paper",
    city: "Vapi",
    state: "Gujarat",
    country: "India",
    lat: 20.37,
    lon: 72.91,
    grade: "Duplex & Triplex Board (Exporter)",
    verified: true,
  },
  {
    slug: "diyan-paper",
    name: "Diyan Papers LLP",
    short: "Diyan Papers",
    city: "Wankaner",
    state: "Gujarat",
    country: "India",
    lat: 22.62,
    lon: 70.93,
    grade: "Duplex Board (Grey Back, White Back), Kraft",
    verified: true,
  },
  {
    slug: "sahota-papers",
    name: "Sahota Papers Limited",
    short: "Sahota Papers",
    city: "Jaspur",
    state: "Uttarakhand",
    country: "India",
    lat: 29.28,
    lon: 78.83,
    grade: "Coated Duplex Board",
    verified: true,
  },

  // ====== INDIA — EAST (Odisha) ======
  {
    slug: "emami-paper",
    name: "Emami Paper Mills",
    short: "Emami Paper",
    city: "Balasore",
    state: "Odisha",
    country: "India",
    lat: 21.49,
    lon: 86.93,
    grade: "Newsprint, Board",
    product: "Netique Deckle Matcher",
    testimonial:
      "We are using your Netique Deckle Matcher software for the last two years and pleased to inform that it is working smoothly. We are satisfied with the system and hope that you will update and modify the system as required times.",
    verified: true,
  },

  {
    slug: "tnpl",
    name: "Tamil Nadu Newsprint and Papers Ltd (TNPL)",
    short: "TNPL",
    city: "Karur",
    state: "Tamil Nadu",
    country: "India",
    lat: 10.96,
    lon: 78.08,
    grade: "Newsprint, W&P",
    verified: true,
  },

  // ====== INTERNATIONAL ======
  {
    slug: "waraq-paper",
    name: "Waraq Paper",
    short: "Waraq Paper",
    city: "Riyadh",
    state: "Riyadh",
    country: "Saudi Arabia",
    lat: 24.71,
    lon: 46.68,
    grade: "Kraft, Tissue",
    verified: true,
  },
  {
    slug: "upm-union",
    name: "UPM Union Paper Mills",
    short: "Union Paper Mills",
    city: "Sharjah",
    state: "Sharjah",
    country: "UAE",
    lat: 25.35,
    lon: 55.4,
    grade: "Kraft, Coated",
    verified: true,
  },
];

// Expanded to cover India + Gulf (Saudi Arabia / UAE)
export const INDIA_BBOX = {
  minLon: 44,
  maxLon: 100,
  minLat: 6,
  maxLat: 36,
};
