export type ModuleData = {
  slug: string;
  tag: string;
  name: string;
  title: string;
  highlight: string;
  blurb: string;
  photo: string;
  accent: string;
  icon: string;
  metrics: { value: string; label: string }[];
  features: {
    tag: string;
    title: string;
    body: string;
    points: string[];
    photo: string;
    flip?: boolean;
  }[];
  workflow: {
    title: string;
    nodes: { id: string; label: string; sub?: string; variant?: "start" | "active" | "end" | "default" }[];
  };
  documentFlow?: {
    title: string;
    nodes: { label: string; sub?: string; highlight?: boolean }[];
  };
  capabilities: { icon: string; title: string; desc: string }[];
  integrations: { module: string; action: string; effect: string }[];
};

export const MODULES_DATA: Record<string, ModuleData> = {
  sales: {
    slug: "sales",
    tag: "Sales & Order Management",
    name: "Sales",
    title: "From inquiry to invoice.",
    highlight: "In one connected flow.",
    blurb: "Complete order-to-cash cycle for paper mills — inquiry capture, multi-version quotations, sales orders with ATP, delivery challans, e-invoicing, payment receipts, returns, and credit notes. GST and FEMA compliant by default.",
    photo: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1920&q=80",
    accent: "#F59E0B",
    icon: "ShoppingCart",
    metrics: [
      { value: "9", label: "order types" },
      { value: "11", label: "doc statuses" },
      { value: "100%", label: "GSTR-1 ready" },
      { value: "180+", label: "API endpoints" },
    ],
    features: [
      {
        tag: "Inquiry & Quotation",
        title: "Capture leads. Price intelligently.",
        body: "Track inquiries with lead scoring, generate versioned quotations with cost breakdown and margin analysis, run revisions, and convert to sales orders with full audit trail.",
        points: [
          "Lead scoring with source conversion analytics",
          "Versioned quotations with diff & rollback",
          "Real-time cost engine + margin validation",
          "Approval workflow with price override gates",
          "Win/loss analysis with competitor intelligence",
          "Validity extension and bulk expiry management",
        ],
        photo: "https://images.unsplash.com/photo-1551836022-deb4988cc6c0?auto=format&fit=crop&w=1200&q=80",
      },
      {
        tag: "Sales Order Lifecycle",
        title: "ATP-checked. Credit-validated. Auditable.",
        body: "Manage 9 order types — Standard, Rush, Export, Sample, Standing, Reel, Sheet, Conversion, and Toll Manufacturing — each with credit checks, batch allocation, and configurable approval matrix.",
        points: [
          "Available-to-Promise (ATP) check on confirm",
          "Automatic batch determination + manual override",
          "Credit limit & exposure validation",
          "Hold/resume workflow with reasons",
          "Multi-stage approval matrix per order type",
          "Real-time order incompletion validation",
        ],
        photo: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80",
        flip: true,
      },
      {
        tag: "Dispatch Control Tower",
        title: "Mill floor to vehicle gate, tracked.",
        body: "Real-time dispatch dashboard with transporter assignment, pick lists, loading gate management, weighbridge integration, and POD capture.",
        points: [
          "Live dispatch queue with priority routing",
          "Bulk transporter assignment for queue clearing",
          "Pick list generation + confirmation workflow",
          "Loading gate in/out + weighbridge reconciliation",
          "POD capture with photo + signature",
          "Vehicle tracking with delivery ETAs",
        ],
        photo: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=1200&q=80",
      },
      {
        tag: "Invoicing & E-Invoice",
        title: "GST-ready invoices. IRN-generated. Always.",
        body: "Create invoices from sales orders or delivery challans with full GST compliance, auto IRN generation via NIC portal, GSTR-1 auto-population, e-Way bills, and amendment tracking.",
        points: [
          "DC-to-Invoice batch conversion",
          "IRN generation with NIC portal health check",
          "Auto-populate GSTR-1 schedule rules",
          "E-Way Bill generation from invoice/DC",
          "Amendment cycle (cancel + new IRN)",
          "Multi-copy PDF with QR + envelope rendering",
        ],
        photo: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80",
        flip: true,
      },
      {
        tag: "Receivables & Collections",
        title: "Get paid. On time. Automatically.",
        body: "Payment receipts with PDC tracking, multi-invoice application, TDS deductions, aging analysis, dunning workflows, dispute management, and bad-debt write-offs.",
        points: [
          "Multi-instrument payments (NEFT/RTGS/IMPS/UPI/Cheque/LC)",
          "Post-dated cheque register with bounce handling",
          "TDS auto-deduction with certificate tracking",
          "Aging analysis with dunning escalation",
          "Interest auto-calculation + debit note generation",
          "Write-off workflow with approval",
        ],
        photo: "https://images.unsplash.com/photo-1556742044-3c52d6e88c62?auto=format&fit=crop&w=1200&q=80",
      },
      {
        tag: "Export & Trade",
        title: "Built for exporters.",
        body: "Full export documentation pipeline — shipping bills, LCs, FTA claims (CEPA, RCEP), high-sea sales, eBRC, Bill of Entry — with FEMA-compliant forex tracking.",
        points: [
          "Shipping Bills with NIC integration",
          "LC management with FEMA tracking",
          "FTA/RoDTEP credit claims",
          "eBRC (Electronic Bank Realisation Certificate)",
          "Bill of Entry for import customs",
          "Forex revaluation + gain/loss accounting",
        ],
        photo: "https://images.unsplash.com/photo-1577416412292-747c6607f055?auto=format&fit=crop&w=1200&q=80",
        flip: true,
      },
    ],
    workflow: {
      title: "Sales Order State Machine",
      nodes: [
        { id: "draft", label: "DRAFT", sub: "create", variant: "start" },
        { id: "sub", label: "SUBMITTED", sub: "submit" },
        { id: "app", label: "APPROVED", sub: "approve", variant: "active" },
        { id: "con", label: "CONFIRMED", sub: "ATP check" },
        { id: "prod", label: "IN_PRODUCTION", sub: "produce" },
        { id: "disp", label: "DISPATCHED", sub: "transporter" },
        { id: "del", label: "DELIVERED", sub: "POD" },
        { id: "inv", label: "INVOICED", sub: "GST IRN" },
        { id: "closed", label: "CLOSED", sub: "paid", variant: "end" },
      ],
    },
    documentFlow: {
      title: "Order-to-Cash Document Flow",
      nodes: [
        { label: "Inquiry", sub: "lead scoring" },
        { label: "Quotation", sub: "versioned" },
        { label: "Sales Order", sub: "ATP", highlight: true },
        { label: "Delivery Challan", sub: "e-Way bill" },
        { label: "Invoice", sub: "IRN", highlight: true },
        { label: "Payment", sub: "TDS" },
        { label: "Credit Note", sub: "if return" },
      ],
    },
    capabilities: [
      { icon: "FileText", title: "Quotation Versioning", desc: "Every quotation revision is captured automatically with a side-by-side diff showing what changed — price, quantity, terms, validity. Roll back to any version with one click. Essential when customers negotiate over multiple rounds." },
      { icon: "ClipboardCheck", title: "Order Approval Matrix", desc: "Configurable multi-tier approval rules by order type, customer, amount, or margin. Orders auto-route to the right approver; nothing slips through without sign-off. Track SLA breaches and escalations from one queue." },
      { icon: "Truck", title: "Dispatch Control Tower", desc: "Single live view of every order ready to dispatch, with transporter assignment, pick lists, gate in/out, and weighbridge reconciliation. Bulk-assign vehicles and clear the queue in minutes instead of hours." },
      { icon: "Receipt", title: "E-Invoice & IRN", desc: "Generate IRN on the NIC portal the moment an invoice is finalized. Auto-populate GSTR-1 schedule, embed QR codes on PDFs, and handle amendments through the cancel-and-reissue cycle. Built for the 30-day IRN window." },
      { icon: "RefreshCw", title: "Returns & Credit Notes", desc: "End-to-end return flow — submit, approve, receive, inspect, restock — with credit note auto-issued on completion. Returns tie back to the originating invoice so margins and GSTR-1 reconcile cleanly." },
      { icon: "Award", title: "Lead Scoring", desc: "Score every inquiry by source, customer value, and conversion history. Sales reps focus on high-probability leads first; managers see source ROI and win-loss patterns. Tunable weighting per business profile." },
      { icon: "Calculator", title: "Cost & Margin Engine", desc: "Live costing breakdown for every quotation line — material, conversion, overhead, freight, tax. Hard-stop on margin floor violations with override-approval workflow. Quote confidently without spreadsheet round-trips." },
      { icon: "Globe", title: "Export Documentation", desc: "Generate shipping bills, packing lists, LC drafts, FTA/RoDTEP claim files, eBRC reconciliations, and Bill of Entry from order data. One source of truth for customs, shipping line, and bank documentation." },
      { icon: "Wallet", title: "Multi-currency", desc: "Quote, invoice, and receive in any currency with auto-revaluation on FX rate changes. FEMA-compliant accounting for export proceeds with forex gain/loss posted to the right GL accounts automatically." },
    ],
    integrations: [
      { module: "Inventory", action: "Order CONFIRMED → batch allocation", effect: "Reserve batches via FEFO" },
      { module: "Production", action: "Order CONFIRMED → work order trigger", effect: "MPS/MRP plan if make-to-order" },
      { module: "Finance", action: "Invoice FINALIZED → AR posting", effect: "GL receivable + revenue recognition" },
      { module: "Finance", action: "E-Invoice → GSTR-1 schedule", effect: "Auto-populate filing register" },
      { module: "Party", action: "Order create → credit check", effect: "Validate limit + exposure" },
      { module: "Email Hub", action: "Status change → notification", effect: "Customer auto-email per workflow" },
    ],
  },

  procurement: {
    slug: "procurement",
    tag: "Procurement & Vendor Management",
    name: "Procurement",
    title: "From requisition to three-way match.",
    highlight: "In hours, not days.",
    blurb: "MRP-driven auto-requisitions, RFQ email bridge for instant supplier quotes, scorecards, 3-way match (PO ↔ GRN ↔ AP Invoice), MSME compliance, and reverse-charge mechanism — all configurable per company.",
    photo: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1920&q=80",
    accent: "#3B82F6",
    icon: "Package",
    metrics: [
      { value: "100%", label: "3-way match" },
      { value: "MRP", label: "auto-PR" },
      { value: "MSME", label: "compliant" },
      { value: "RCM", label: "ITC ready" },
    ],
    features: [
      {
        tag: "Smart Sourcing",
        title: "MRP creates the PR. We do the rest.",
        body: "Auto-generated purchase requisitions from MRP explosion, RFQ email bridge for instant supplier quotes, multi-attribute quotation scoring, and vendor scorecard management.",
        points: [
          "MRP-driven auto-PR generation",
          "RFQ email bridge for supplier responses",
          "Multi-attribute quotation scoring (price + lead time + quality)",
          "Vendor scorecard with delivery performance",
          "Bulk PO generation from approved PRs",
          "PR-to-PO conversion with budget gates",
        ],
        photo: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80",
      },
      {
        tag: "Three-Way Match",
        title: "PO ↔ GRN ↔ AP Invoice. Reconciled.",
        body: "Every PO line is matched against goods received (GRN) and supplier invoice (AP) with tolerance rules. Variances are flagged, blocked, or auto-approved by configurable thresholds.",
        points: [
          "Automatic 3-way matching on PO + GRN + AP invoice",
          "Configurable tolerance: qty / price / amount",
          "Variance routing to approver",
          "MSME 45-day payment enforcement",
          "Hold-payment-on-mismatch policy",
          "RCM reverse charge reconciliation",
        ],
        photo: "https://images.unsplash.com/photo-1573164574572-cb89e39749b4?auto=format&fit=crop&w=1200&q=80",
        flip: true,
      },
      {
        tag: "Indian Compliance",
        title: "GST. TDS. TCS. RCM. MSME. Native.",
        body: "Every supplier transaction respects Indian tax law — automatic TDS deduction per section, GST/TCS handling, RCM journal entries, and MSME payment-window enforcement.",
        points: [
          "Section-wise TDS auto-deduction (194C, 194H, 194J, etc.)",
          "GST input credit reconciliation (ITC ledger)",
          "RCM journal posting for unregistered suppliers",
          "MSME Udyam registration validation",
          "TCS Section 206C handling",
          "Vendor blacklist with reason tracking",
        ],
        photo: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80",
      },
    ],
    workflow: {
      title: "Procurement Document Flow",
      nodes: [
        { id: "pr", label: "PR", sub: "from MRP", variant: "start" },
        { id: "rfq", label: "RFQ", sub: "to suppliers" },
        { id: "quot", label: "Quotation", sub: "scored" },
        { id: "po", label: "PO", sub: "approved", variant: "active" },
        { id: "grn", label: "GRN", sub: "received" },
        { id: "qc", label: "QC", sub: "inspection" },
        { id: "inv", label: "AP Invoice", sub: "matched" },
        { id: "pay", label: "Payment", sub: "TDS applied", variant: "end" },
      ],
    },
    capabilities: [
      { icon: "ListChecks", title: "Auto-PR from MRP", desc: "MRP runs explode net demand and automatically draft purchase requisitions per supplier, with lead time, MOQ, and safety stock applied. Procurement reviews suggestions instead of building them from scratch — slashes PR creation time by 80%." },
      { icon: "Mail", title: "RFQ Email Bridge", desc: "Send RFQs to suppliers as structured emails; their reply is parsed back into a comparable quotation row. No supplier portal logins required — they just reply to your email and quotes appear in the comparison grid." },
      { icon: "Award", title: "Vendor Scorecards", desc: "Score every supplier on delivery, quality, price competitiveness, MSME status, and response time. Live scorecards inform sourcing decisions; underperformers get auto-flagged and can be moved to provisional or blacklisted status." },
      { icon: "Shield", title: "3-Way Match", desc: "Auto-match PO line → GRN line → AP invoice line with configurable qty/price/amount tolerance. Mismatches block payment release and route to the right approver. Eliminates over-payment and supplier-side errors." },
      { icon: "Calendar", title: "MSME Enforcement", desc: "Detect MSME/Udyam-registered suppliers from GSTIN and apply the statutory 45-day payment window automatically. Track exposure to MSMEs in real time; avoid Section 43B(h) tax disallowance with proactive alerts." },
      { icon: "Calculator", title: "TDS Auto-deduct", desc: "Apply correct TDS section (194C, 194H, 194J, 194Q, etc.) based on supplier type and transaction. Generates Form 26Q-ready data; quarterly returns export with one click. No manual rate lookup, no missed deductions." },
      { icon: "RefreshCw", title: "RCM Reverse Charge", desc: "Auto-post reverse charge journal entries for unregistered or specified-category suppliers. ITC eligibility tracked separately; GSTR-3B inward supplies under RCM populates from real transactions." },
      { icon: "AlertCircle", title: "Variance Routing", desc: "Configure tolerance ranges per material/supplier; price or qty deltas above threshold route to commercial team with the GRN/PO context attached. Approve or reject in the inbox; full audit trail per decision." },
      { icon: "Database", title: "ITC Reconciliation", desc: "Match supplier GSTR-1 entries against your inward supplies; mismatches surface immediately. Track ITC eligibility, reversal triggers (180-day rule, blocked credits), and the ledger balance carried into GSTR-3B." },
    ],
    integrations: [
      { module: "Inventory", action: "PO → GRN", effect: "Goods receipt with batch labels" },
      { module: "Finance", action: "AP Invoice → GL", effect: "Payable posting + TDS journal" },
      { module: "Production", action: "MRP → Auto-PR", effect: "Material requisition from BOM" },
      { module: "Party", action: "Vendor selection → credit terms", effect: "Pull payment window + MSME flag" },
      { module: "Approvals", action: "PO/PR → matrix", effect: "Route by amount + department" },
      { module: "Finance", action: "Three-way match → payment release", effect: "Block payment on mismatch" },
    ],
  },

  production: {
    slug: "production",
    tag: "Production Planning & Execution",
    name: "Production",
    title: "From schedule to settled WO.",
    highlight: "Every reel. Every shift. Accounted for.",
    blurb: "Complete paper mill manufacturing — MPS/MRP/CRP planning, Gantt scheduling with grade-change optimization, work order lifecycle, shop floor execution, reel tracking, OEE analytics, lab QC, downtime management, and what-if scenario analysis. Purpose-built for paper mill operations.",
    photo: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=1920&q=80",
    accent: "#F97316",
    icon: "Factory",
    metrics: [
      { value: "3-Layer", label: "MPS + MRP + CRP" },
      { value: "7-State", label: "WO lifecycle" },
      { value: "OEE", label: "live per machine" },
      { value: "SPC", label: "real-time control" },
    ],
    features: [
      {
        tag: "Planning Layers",
        title: "MPS. MRP. CRP. Connected.",
        body: "Three-layer planning engine — Master Production Schedule with bucket-based horizons and frozen periods, MRP explosion using multi-level BOMs with lot-sizing (LOT_FOR_LOT, EOQ, POQ, MIN_MAX), and CRP capacity load analysis with bottleneck identification. Planning exceptions surface material shortages, capacity overloads, and lead-time violations before they hit the floor.",
        points: [
          "Bucket-based MPS (DAY/WEEK/MONTH/QUARTER) with freeze periods",
          "Net-change MPS — append demand without full re-plan",
          "MRP explosion: multi-level BOM with scrap + yield factors",
          "Lot sizing: LOT_FOR_LOT, EOQ, POQ, MIN_MAX per item",
          "CRP load analysis with infinite/finite capacity simulation",
          "Exception engine: shortage, capacity overload, lead-time, safety-stock",
          "Demand forecasting: moving average, exponential smoothing, seasonal",
          "Forecast-to-demand consumption tracking",
        ],
        photo: "https://images.unsplash.com/photo-1551836022-deb4988cc6c0?auto=format&fit=crop&w=1200&q=80",
      },
      {
        tag: "Production Scheduling",
        title: "Gantt plans. Grade-change optimized.",
        body: "Schedule creation, versioning, and approval workflow with a full Gantt timeline view. Runs are sequenced with grade-change optimization — a penalty matrix predicts waste and downtime for every transition type (within-family, cross-family, colour change, full wash) and recommends the lowest-cost sequence. Conflict detection flags overlaps, capacity breaches, maintenance windows, and shift gaps before release.",
        points: [
          "Schedule lifecycle: DRAFT → IN_REVIEW → RELEASED → COMPLETED",
          "Gantt timeline with drag-and-drop run sequencing",
          "Grade-change optimization with waste/downtime penalty matrix",
          "Transition types: WITHIN_FAMILY, CROSS_FAMILY, COLOR_CHANGE, FULL_WASH",
          "Confidence-scored transition cost predictions vs actual tracking",
          "Conflict detection: overlap, capacity, maintenance, shift-gap",
          "Freeze windows to protect released schedules from edits",
          "Auto-schedule from demand → schedule-to-WO conversion",
        ],
        photo: "https://images.unsplash.com/photo-1565793498704-9cb936e92524?auto=format&fit=crop&w=1200&q=80",
        flip: true,
      },
      {
        tag: "Work Order Lifecycle",
        title: "Seven states. Zero gaps.",
        body: "Full work order management from CREATED to CLOSED — BOM + routing explosion on release, material reservation and bulk or line-item issue, labour entries by role (PRIMARY / SECONDARY / HELPER / SUPERVISOR), real-time cost accumulation (material + labour + overhead), QC integration, rework WO auto-creation on failure, split WO, hold/resume, and cost variance settlement.",
        points: [
          "States: CREATED → RELEASED → IN_PROGRESS → COMPLETED → CLOSED / HELD / CANCELLED",
          "BOM + routing explosion on release; blocked if active version missing",
          "Material reservation and Goods Issue (bulk or line-by-line)",
          "Labour entry with role classification and overtime tracking",
          "Machine transition logging with start/end timestamps and downtime reason",
          "Real-time WO costing: material + labour + utility + overhead",
          "QC pass/fail with auto rework WO and FG receipt block on fail",
          "Split WO, bulk release/cancel, cost variance settlement with approval",
        ],
        photo: "https://images.unsplash.com/photo-1565793298495-4f3c61ee7ec1?auto=format&fit=crop&w=1200&q=80",
      },
      {
        tag: "Shop Floor Execution",
        title: "Live mill. Real numbers.",
        body: "Production entries per shift per machine — actual speed, output, reel counts, defect logging, material and utility consumption, operator notes, and supervisor approval. Reel quality recorded at point of creation (GSM, brightness, moisture, freeness, opacity). Shift allotment manages crew assignment, break scheduling, and night-shift premium. Shift reports export to PDF with approval audit trail.",
        points: [
          "Real-time machine status dashboard with live OEE overlay",
          "Production entries: actual speed, output, duration per shift",
          "Reel creation with quality readings (GSM, brightness, moisture, opacity)",
          "Reel grades: a_grade, b_grade, c_grade, waste — with defect position tracking",
          "Defect severity: Minor, Major, Critical with root-cause categorization",
          "Utility consumption tracking: electricity, steam, water, fuel",
          "Shift allotment: crew assignment, breaks, night-shift premium validation",
          "Shift report PDF with submit → approve → reject workflow",
        ],
        photo: "https://images.unsplash.com/photo-1581094271901-8022df4466f9?auto=format&fit=crop&w=1200&q=80",
        flip: true,
      },
      {
        tag: "Quality & Lab",
        title: "Inspect. Test. Certify.",
        body: "Quality inspections at WO or reel level with DRAFT → FINALIZED → RELEASED workflow. Lab parameters validated against product, customer, or template tolerances — brightness, freeness, ash, moisture, caliper, opacity, tensile. Certificate of Analysis generated in PDF. NCR raised on failure routes to CAPA with 5-Why, corrective action, verification, and auditor-ready evidence trail.",
        points: [
          "Inspection at WO level or individual reel level",
          "Parameter pass/fail against product / customer / template spec",
          "Lab parameters: brightness, freeness CSF, ash, moisture, caliper, tensile",
          "Certificate of Analysis (COA) PDF with parameter actuals vs limits",
          "FG receipt blocked until QC inspection RELEASED",
          "SPC control limits per parameter with real-time violation alerts",
          "NCR (non-conformance) → CAPA with 5-Why root cause analysis",
          "Quality sort: prime / second / third / broke with disposition workflow",
        ],
        photo: "https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&w=1200&q=80",
      },
      {
        tag: "Analytics & OEE",
        title: "Know every loss. Fix the right one.",
        body: "OEE per machine broken into availability, performance, and quality components with waterfall loss analysis and period-over-period trending. Cost analytics tracks material, labour, utility, and overhead per tonne by grade or machine. Yield Sankey diagrams show material flow from raw input to finished goods. Custom report builder with scheduled distribution.",
        points: [
          "OEE = Availability × Performance × Quality, live per machine",
          "OEE loss waterfall: which component is dragging it down",
          "Cost per tonne by grade, machine, shift — budget vs actual variance",
          "Yield Sankey: material flow from raw input to FG",
          "Defect Pareto with drill-down to root-cause category",
          "SPC control charts with Western Electric rule violation flagging",
          "Custom report builder with metric selection and scheduled distribution",
          "Energy analytics: kWh/tonne, steam/tonne vs benchmarks, anomaly detection",
        ],
        photo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
        flip: true,
      },
      {
        tag: "Downtime & Optimization",
        title: "Quantify loss. Act on it.",
        body: "Downtime events recorded with reason categories (planned, unplanned), machine assignment, duration, and cost impact. Optimization engine generates recommendations — grade-change sequencing, energy anomaly resolution, process parameter tuning — with estimated INR savings, confidence scores, and implementation tracking. What-if scenario analysis lets planners simulate speed changes, grade swaps, or shift patterns before committing.",
        points: [
          "Downtime events: planned vs unplanned, reason category, cost impact",
          "Corrective action tracking per downtime event",
          "Optimization recommendations: DRAFT → ACTIVE → IMPLEMENTED lifecycle",
          "Estimated savings in INR with confidence score per recommendation",
          "What-if scenarios: change speed, grade, shift — predict output and cost",
          "Energy anomaly detection with suspected cause and resolution workflow",
          "Grade-change sequence optimizer with actual vs predicted tracking",
          "Downtime Pareto by machine, reason, shift for maintenance prioritization",
        ],
        photo: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
      },
      {
        tag: "Resource & Labour Planning",
        title: "Right crew. Right machine. Costed.",
        body: "Resource definitions (machines, work centres, labour, utilities) with availability calendars and capacity constraints. Employee rates configured by role and rate type (hourly, overtime, night premium). Crew assignments per shift with skill tracking (operator, supervisor, maintenance). Overtime requests route through approval. All labour costs roll into WO cost in real time.",
        points: [
          "Resource availability calendars with capacity constraint definitions",
          "Employee rate master: hourly, overtime, night-shift premium by role",
          "Crew assignment per shift with skill classification",
          "Overtime request → approval → WO cost roll-up",
          "Resource conflict detection: two allocations same machine/person same slot",
          "Capacity utilization dashboard: over/under-capacity alerts",
          "Process parameter targets per product/machine with actual vs target trending",
          "Chemical dosing records: target rate vs actual, variance alerts",
        ],
        photo: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80",
        flip: true,
      },
    ],
    workflow: {
      title: "Work Order State Machine",
      nodes: [
        { id: "cre", label: "CREATED", variant: "start" },
        { id: "rel", label: "RELEASED", sub: "BOM exploded" },
        { id: "prog", label: "IN_PROGRESS", sub: "operations", variant: "active" },
        { id: "comp", label: "COMPLETED", sub: "reels in" },
        { id: "qc", label: "QC", sub: "pass/fail" },
        { id: "closed", label: "CLOSED", sub: "settled", variant: "end" },
      ],
    },
    capabilities: [
      { icon: "Workflow", title: "MPS / MRP / CRP", desc: "Three planning layers working together — Master Production Schedule sets the horizon, MRP explodes demand into purchase plans using multi-level BOMs with configurable lot-sizing, CRP checks machine load. Surfaces shortages, capacity overloads, and lead-time violations before production starts." },
      { icon: "CalendarDays", title: "Gantt Scheduling", desc: "Full schedule lifecycle from DRAFT to COMPLETED with Gantt timeline, drag-and-drop run sequencing, version control, and approval workflow. Schedule releases convert to work orders automatically. Freeze windows prevent edits to live schedules." },
      { icon: "GitBranch", title: "BOM Explosion", desc: "When a work order releases, the active BOM and routing automatically populate material lines and operation sequences. Release is blocked if any active version is missing — protects against half-defined runs hitting the shop floor." },
      { icon: "Cog", title: "Grade-Change Optimization", desc: "Penalty matrix models waste and downtime for every transition type (within-family, cross-family, colour change, full wash). The optimizer recommends the lowest-cost grade sequence for each schedule; predictions are tracked against actuals and the model self-refines." },
      { icon: "Activity", title: "Live OEE", desc: "Real-time Overall Equipment Effectiveness per machine — availability × performance × quality. OEE loss waterfall shows which component is dragging it down. Trend shift over shift, compare machines, and surface the biggest improvement opportunity." },
      { icon: "BarChart2", title: "SPC Control Charts", desc: "Statistical Process Control charts for GSM, brightness, moisture, freeness, opacity, and other quality parameters. Control limits defined per parameter per machine. Auto-flag out-of-control runs with Western Electric rules; operators see violations live." },
      { icon: "ClipboardCheck", title: "QC Workflow", desc: "Reel-level or WO-level inspection with parameter-by-parameter pass/fail against product or customer spec. Failed batches block FG receipt; passed batches auto-generate a Certificate of Analysis (COA) PDF ready for dispatch." },
      { icon: "AlertCircle", title: "NCR / CAPA", desc: "Log non-conformances against the offending batch, route to engineering for 5-Why root cause analysis, track corrective and preventive actions to closure with effectiveness verification. Full audit-ready evidence trail." },
      { icon: "Timer", title: "Downtime Tracking", desc: "Every downtime event recorded with reason category, planned vs unplanned flag, start/end times, duration, and cost impact. Corrective actions tracked per event. Downtime Pareto by machine, reason category, and shift drives maintenance prioritization." },
      { icon: "Lightbulb", title: "Optimization Recommendations", desc: "The engine generates recommendations for grade-change sequencing, energy anomaly resolution, and process tuning — each with an estimated INR saving and confidence score. Recommendations flow through DRAFT → ACTIVE → IMPLEMENTED with savings validation." },
      { icon: "FlaskConical", title: "What-If Scenarios", desc: "Simulate proposed changes before committing — change machine speed, swap grade, alter shift pattern. The engine predicts output tonnage, cost per tonne, quality index, and machine utilization. Side-by-side comparison; promote the winning scenario to a real schedule." },
      { icon: "Users", title: "Resource & Labour", desc: "Employee rate master with hourly, overtime, and night-shift premium by role. Crew assignment per shift with skill classification. Overtime request/approval flow. All labour costs roll into WO cost in real time. Capacity utilization dashboard with over/under-capacity alerts." },
    ],
    integrations: [
      { module: "Inventory", action: "WO release → Material Issue", effect: "Stock ledger consumption posted in real time" },
      { module: "Inventory", action: "WO complete → FG batch", effect: "Finished goods batch auto-created on QC pass" },
      { module: "Product Catalog", action: "WO release → BOM check", effect: "Release blocked if no active BOM or routing version" },
      { module: "Finance", action: "WO close → cost settlement", effect: "Variance posted to GL; overhead absorption calculated" },
      { module: "Sales", action: "SO confirmed → MPS demand", effect: "Net-change demand added to MPS automatically" },
      { module: "HR", action: "Labor entry → cost rollup", effect: "Employee rates pulled; overtime flagged for approval" },
      { module: "Maintenance", action: "Downtime event → work request", effect: "Unplanned downtime auto-raises maintenance work request" },
      { module: "Deckle Optimizer", action: "Schedule run → slit plan", effect: "Grade/width from schedule feeds deckle optimization" },
    ],
  },

  deckle: {
    slug: "deckle",
    tag: "Deckle Optimizer",
    name: "Deckle Optimizer",
    title: "Eliminate trim waste.",
    highlight: "Maximize reel recovery.",
    blurb: "Proprietary three-tier optimization engine for paper mill slitting plans. From reactive mid-shift adjustments (<2s) to fully optimal daily plans with 180+ constraints (≤5 min). Saves mills ₹100K+ per month.",
    photo: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1920&q=80",
    accent: "#EF4444",
    icon: "Scissors",
    metrics: [
      { value: "3-Tier", label: "engine" },
      { value: "180+", label: "constraints" },
      { value: "<2s", label: "instant mode" },
      { value: "₹100K+", label: "monthly savings" },
    ],
    features: [
      {
        tag: "3-Tier Optimization",
        title: "Right algorithm. Right time budget.",
        body: "Instant Mode for mid-shift quick fixes (<2 sec), Planning Mode for shift-level decisions (5-30 sec), Full Optimization for daily plans with 180+ constraints (≤5 min). Auto-selects based on time budget and problem size.",
        points: [
          "Instant Mode: <2s for mid-shift adjustments",
          "Planning Mode: 5-30s for shift-level planning",
          "Full Optimization: ≤5 min with 180+ constraints",
          "Automatic tier selection by problem complexity",
          "Live progress streaming during optimization",
          "Cancellable runs with cleanup",
        ],
        photo: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80",
      },
      {
        tag: "Explainability",
        title: "Every plan, justified.",
        body: "Each optimization output shows active constraints, alternative patterns evaluated, recovery analysis, position scoring, and trade-off reasoning. Not a black box — a transparent decision tool.",
        points: [
          "Active constraint visualization",
          "Alternative pattern comparison",
          "Recovery analysis per SWO position",
          "Position scoring with trade-off reasoning",
          "Pattern effectiveness analytics",
          "Plan vs. actual reconciliation",
        ],
        photo: "https://images.unsplash.com/photo-1554224154-22dec7ec8818?auto=format&fit=crop&w=1200&q=80",
        flip: true,
      },
      {
        tag: "Pattern Learning",
        title: "Engine learns from your mill.",
        body: "Auto-captures approved plans, learns proven patterns over multiple runs, applies them to future optimizations. Your operators' expertise compounds into the engine.",
        points: [
          "Auto-capture of approved plans",
          "Proven pattern recognition over multiple runs",
          "Pattern library with effectiveness scoring",
          "Customer tolerance learning",
          "Grade substitution rules",
          "Position constraint refinement over time",
        ],
        photo: "https://images.unsplash.com/photo-1517420704952-d9f39e95b43e?auto=format&fit=crop&w=1200&q=80",
      },
      {
        tag: "Configuration",
        title: "15+ tunable knobs.",
        body: "Configure constraints (speed, capacity, quality), optimization profiles, priority weighting, SWO settings, machine chains, allowance rules, position constraints, OD grouping, and cost overrides — per company or per grade.",
        points: [
          "Constraint profiles (speed/capacity/quality)",
          "Optimization profile cloning + defaults",
          "Priority profiles with weighted scoring",
          "SWO config: shifts + changeovers",
          "Machine chains: serial setup + grade matrix",
          "Allowance rules: pocket / reel / machine-specific",
          "Cost config per company + grade overrides",
        ],
        photo: "https://images.unsplash.com/photo-1517420704952-d9f39e95b43e?auto=format&fit=crop&w=1200&q=80",
        flip: true,
      },
      {
        tag: "Standalone / Pluggable",
        title: "Already running SAP? Use Deckle anyway.",
        body: "Deckle Optimizer ships as a standalone module that plugs into your existing ERP — SAP, Oracle, Tally, Microsoft Dynamics, or any in-house API-enabled system. Send demand in, get optimized plans back. No need to replace what's already working.",
        points: [
          "Standalone deployment: cloud, on-prem, or hybrid",
          "REST APIs for demand input, plan output, status streaming",
          "Pre-built connectors: SAP S/4HANA, Oracle ERP, Tally, MS Dynamics",
          "Custom integration in days via OpenAPI spec",
          "SSO with corporate identity (SAML, OIDC, AD)",
          "Plan release back into your ERP as production orders",
          "Works alongside, not instead of, your existing systems",
        ],
        photo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
      },
    ],
    workflow: {
      title: "Optimization Run Flow",
      nodes: [
        { id: "demand", label: "Demand", sub: "from SO", variant: "start" },
        { id: "tier", label: "Tier Select", sub: "auto" },
        { id: "opt", label: "Optimize", sub: "constraints", variant: "active" },
        { id: "plan", label: "Plan", sub: "patterns" },
        { id: "review", label: "Review", sub: "drag-drop" },
        { id: "approve", label: "Approve", sub: "audit log" },
        { id: "exec", label: "Execute", sub: "machine", variant: "end" },
      ],
    },
    capabilities: [
      { icon: "Zap", title: "Instant Mode", desc: "Sub-2-second optimization for mid-shift adjustments. When a customer order changes or a reel is rejected, get an updated slitting plan before the operator misses a beat. Trades absolute optimality for speed when you can't wait." },
      { icon: "Brain", title: "Planning Mode", desc: "5–30 second optimization for shift-level decisions. The right balance of quality and speed for the planner's morning meeting — better plans than Instant, fast enough that no one waits." },
      { icon: "Target", title: "Full Optimization", desc: "Up to 5 minutes solving with 180+ constraints — every pocket rule, allowance, customer spec, machine limit. For the daily plan when squeezing the last percent of recovery matters. Saves ₹100K+/month per machine." },
      { icon: "Eye", title: "Explainable Plans", desc: "Every plan shows which constraints were active, which alternatives were considered, and why the chosen pattern won. No black box — planners learn the engine's logic and trust it." },
      { icon: "Layers", title: "Pattern Learning", desc: "Captures every approved plan and learns proven patterns over time. When similar demand comes in, the engine biases toward patterns operators have validated — your team's expertise compounds into the optimizer." },
      { icon: "Cog", title: "15+ Config Areas", desc: "Tunable constraints, optimization profiles, priority weights, SWO config, machine chains, allowance rules, position constraints, cost models — all configurable per company and per grade without code changes." },
      { icon: "GitBranch", title: "Multi-machine Compare", desc: "Same demand pool, multiple machines — see plans side-by-side and split demand intelligently. Optimizer recommends the best allocation; planner overrides where business context demands it." },
      { icon: "RefreshCw", title: "Plan vs. Actual", desc: "Reconcile what was planned against what actually ran. Variance feeds back into pattern learning and cost models — the engine gets smarter every shift, and you have data for continuous improvement projects." },
      { icon: "FileCheck", title: "PDF Export", desc: "Release approved plans as production-ready PDFs with cutting patterns, reel allocations, and operator instructions. Plans can be locked once released; revisions create new versions with full audit trail." },
    ],
    integrations: [
      { module: "Sales", action: "Demand → optimization input", effect: "Pull confirmed SO requirements" },
      { module: "Inventory", action: "Plan → reel allocation", effect: "Reserve reels for slitting" },
      { module: "Production", action: "Plan release → WO", effect: "Auto-create work order on approve" },
      { module: "Finance", action: "Plan → cost analysis", effect: "Sellable recovery vs. waste valuation" },
    ],
  },

  inventory: {
    slug: "inventory",
    tag: "Inventory & Batch Management",
    name: "Inventory",
    title: "Batch-level precision.",
    highlight: "Reel-level traceability.",
    blurb: "From goods receipt to finished reel — full lot traceability with FEFO allocation, reel serial numbering, multi-warehouse, QC holds, sampling plans, cycle counts, recall management, and consignment stock.",
    photo: "https://images.unsplash.com/photo-1553413077-190dd305871c?auto=format&fit=crop&w=1920&q=80",
    accent: "#8B5CF6",
    icon: "Boxes",
    metrics: [
      { value: "FEFO", label: "allocation" },
      { value: "5", label: "GRN types" },
      { value: "QR", label: "batch labels" },
      { value: "100%", label: "traceability" },
    ],
    features: [
      {
        tag: "GRN Workflow",
        title: "Receive. Inspect. Decide. Post.",
        body: "Multi-stage Goods Receipt Note workflow with inspection verification, per-line QC, usage decision capture, and stock posting. Five GRN types: Purchase, Return, Transfer, Production, Opening Stock, FG Direct.",
        points: [
          "Five GRN types covering every receipt scenario",
          "Inspection workflow with per-parameter pass/fail",
          "Usage decision: accept / conditional / rework / return",
          "3-way match (PO ↔ GRN ↔ AP Invoice)",
          "Batch label generation (A6 PDF) with QR codes",
          "Auto putaway with overflow bin handling",
        ],
        photo: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80",
      },
      {
        tag: "Batch Management",
        title: "Every batch. Tracked. Traceable.",
        body: "Comprehensive batch management with split/merge operations, QC hold/release, expiry/retest dates, paper-industry quality parameters (GSM, brightness, moisture, opacity), and customer order allocation.",
        points: [
          "Batch types: Purchase / Production / Adjustment / Transfer / Opening",
          "Split (child batches) and merge operations",
          "QC hold and release workflow",
          "Manufacturing / expiry / retest date tracking",
          "Paper industry parameters: GSM, brightness, moisture, opacity",
          "Customer allocation with availability validation",
          "FEFO suggestions with auto-block on expiry",
        ],
        photo: "https://images.unsplash.com/photo-1565793298495-4f3c61ee7ec1?auto=format&fit=crop&w=1200&q=80",
        flip: true,
      },
      {
        tag: "Movement & Valuation",
        title: "FIFO. Weighted-average. Multi-warehouse.",
        body: "Real-time stock movements with FIFO/weighted-average valuation, multi-warehouse transfers with in-transit tracking, stock adjustments, and complete movement ledger with GL integration.",
        points: [
          "FIFO / weighted-average valuation",
          "Multi-warehouse hierarchical locations",
          "Stock transfer: Draft → Approved → Dispatched → Received",
          "In-transit tracking with overdue/ETA alerts",
          "Stock adjustment with approval + posting",
          "Complete movement ledger with GL bridges",
        ],
        photo: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=1200&q=80",
      },
      {
        tag: "Physical Verification",
        title: "Cycle counts. Blind mode. Barcode-driven.",
        body: "Define verification scope, auto-populate from ledger, record counts in blind mode with barcode scanning, multi-round recounts for high-variance items, threshold-based flagging, and auto stock adjustment posting.",
        points: [
          "Scope by warehouse / location / product",
          "Auto-populate from stock ledger",
          "Blind count mode with barcode scanning",
          "Multi-round recounts for high-variance items",
          "Threshold-based variance flagging (default 5%)",
          "Auto-create stock adjustments on post",
        ],
        photo: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80",
        flip: true,
      },
      {
        tag: "Quality & Recall",
        title: "NCR. Sampling. Recall management.",
        body: "Quality non-conformance records, sampling plans with lot acceptance, CAPA workflow, and product recall management with affected-order traceability — critical for ISO 9001 and food-safety audits.",
        points: [
          "Quality NCR (non-conformance) records",
          "Sampling plans with lot acceptance",
          "CAPA (corrective & preventive action)",
          "Recall management with stock holds",
          "Lot serialization (batch-level serial numbers)",
          "Consignment stock tracking",
        ],
        photo: "https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&w=1200&q=80",
      },
    ],
    workflow: {
      title: "GRN State Machine",
      nodes: [
        { id: "draft", label: "DRAFT", variant: "start" },
        { id: "sub", label: "SUBMITTED", sub: "3-way match" },
        { id: "insp", label: "INSPECTION", sub: "verified" },
        { id: "qc", label: "QC_PENDING", sub: "test results", variant: "active" },
        { id: "app", label: "APPROVED", sub: "usage decision" },
        { id: "post", label: "POSTED", sub: "stock ledger", variant: "end" },
      ],
    },
    capabilities: [
      { icon: "ScanLine", title: "Barcode Scanning", desc: "Scan barcodes during GRN receipt or physical verification — product lookup is instant, no manual SKU entry, no transposition errors. Works with consumer-grade scanners or rugged industrial devices via the mobile app." },
      { icon: "Layers", title: "Batch Split / Merge", desc: "Split a parent batch into children when partial allocation is needed, or merge compatible batches to consolidate stock. Quality status and parentage are preserved so you can trace back to the original receipt." },
      { icon: "Lock", title: "QC Hold", desc: "Place any batch on quality hold to block consumption until cleared — for retest, customer complaint investigation, or supplier issue review. Allocations are auto-released; production can't accidentally pull held stock." },
      { icon: "Calendar", title: "FEFO Allocation", desc: "First-Expire-First-Out batch suggestions for every customer order. Expiring stock moves first; expired stock is auto-blocked. Critical for grades with shelf-life or moisture-sensitive paper." },
      { icon: "Truck", title: "Multi-warehouse", desc: "Manage hierarchical warehouses, zones, and bins across plants. Inter-warehouse transfers track in-transit stock with ETA monitoring; receipts auto-update destination ledger and clear source reservation." },
      { icon: "ClipboardCheck", title: "Cycle Counts", desc: "Schedule physical verification by warehouse, location, or product. Blind-count mode hides expected qty from counters; multi-round recounts on high-variance items; auto-create stock adjustments on post." },
      { icon: "AlertCircle", title: "Recall Management", desc: "Trace any batch back to source materials and forward to every order it shipped on. Issue a recall, generate customer notifications, and freeze affected stock — all from one screen. ISO 22000 / food-safety audit ready." },
      { icon: "Database", title: "Stock Ledger", desc: "Every receipt, issue, transfer, and adjustment posts to an immutable ledger with timestamp, document reference, and user. Drill into any batch's complete history; reconcile against GL with one click." },
      { icon: "FileCheck", title: "Label Generation", desc: "Auto-generate A6 batch labels with QR codes embedding batch ID, GSM, brightness, expiry. Print on labelers or thermal printers; scan at any downstream stage to look up batch and quality data instantly." },
    ],
    integrations: [
      { module: "Procurement", action: "PO → GRN receipt", effect: "Auto-create draft on PO" },
      { module: "Production", action: "WO complete → FG batch", effect: "New finished goods batch" },
      { module: "Sales", action: "SO confirm → allocation", effect: "FEFO batch reservation" },
      { module: "Finance", action: "Stock movement → GL", effect: "Auto-post valuation entries" },
      { module: "Quality", action: "QC fail → NCR", effect: "Non-conformance record" },
    ],
  },

  finance: {
    slug: "finance",
    tag: "Finance & GST Compliance",
    name: "Finance",
    title: "Indian compliance, native.",
    highlight: "Not bolted on.",
    blurb: "GSTR-1/3B auto-filing, ITC ledger, TDS/TCS/RCM auto-deductions, FEMA tracking, LC management, forex revaluation, cost accounting per machine and grade, and trade finance — all built for Indian paper manufacturing.",
    photo: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1920&q=80",
    accent: "#10B981",
    icon: "IndianRupee",
    metrics: [
      { value: "GSTR-1/3B", label: "auto-filing" },
      { value: "FEMA", label: "compliant" },
      { value: "ITC", label: "ledger" },
      { value: "LC", label: "trade finance" },
    ],
    features: [
      {
        tag: "GST Compliance",
        title: "GSTR-1. GSTR-3B. ITC. Automated.",
        body: "GSTR-1 auto-population from e-invoices, GSTR-3B preparation with ITC ledger, RCM journal entries for unregistered suppliers, TCS Section 206C handling, and FEMA tracking for forex transactions.",
        points: [
          "GSTR-1 auto-population from e-invoice schedule",
          "GSTR-3B preparation with ITC ledger",
          "Input Tax Credit ledger with reversal tracking",
          "RCM (Reverse Charge Mechanism) auto-posting",
          "TCS Section 206C handling",
          "FEMA tracking for forex transactions",
        ],
        photo: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80",
      },
      {
        tag: "GL & Periods",
        title: "Chart of accounts. Journals. Period close.",
        body: "Complete general ledger with hierarchical chart of accounts, journal entries with reversal workflow, fiscal period management, trial balance, and period-end closing procedures.",
        points: [
          "Hierarchical chart of accounts (COA tree)",
          "Journal entries: DRAFT → POSTED with reversal",
          "Accrual reversal workflow",
          "Fiscal period management",
          "Trial balance with drill-down",
          "Period-end closing with checks",
        ],
        photo: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80",
        flip: true,
      },
      {
        tag: "AP / AR",
        title: "Payables. Receivables. Aging.",
        body: "Supplier invoice management with approval workflow, customer invoice posting and collection, aging analysis for both AP and AR, and reconciliation against GL.",
        points: [
          "AP invoice approval + payment workflow",
          "Supplier payment with TDS auto-deduction",
          "AP aging (30/60/90/120+)",
          "AR invoice posting to GL",
          "Customer receipt application",
          "AR aging with collection priority",
        ],
        photo: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?auto=format&fit=crop&w=1200&q=80",
      },
      {
        tag: "Costing & Budgets",
        title: "Standard cost. Variance. Budget control.",
        body: "Product costing per grade/machine, cost center allocation, actual-vs-standard variance analysis, budget management with revision workflow, and lock-on-publish governance.",
        points: [
          "Product costing per grade and machine",
          "Cost center hierarchy",
          "Standard vs. actual variance analysis",
          "Budget creation + revision workflow",
          "Budget lock with read-only mode",
          "Landed cost for imported materials",
        ],
        photo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
        flip: true,
      },
      {
        tag: "Trade Finance",
        title: "LC. Invoice discounting. Insurance. ECGC.",
        body: "Letter of Credit management with FEMA tracking, invoice discounting for supply chain finance, trade insurance, ECGC claim management, and forex revaluation with FX gain/loss accounting.",
        points: [
          "LC management with FEMA compliance",
          "Invoice discounting for SCF",
          "Trade insurance tracking",
          "ECGC (Export Credit Guarantee) claims",
          "Forex revaluation: FX gain/loss",
          "Multi-currency journal entries",
        ],
        photo: "https://images.unsplash.com/photo-1559526324-c1f275fbfa32?auto=format&fit=crop&w=1200&q=80",
      },
    ],
    workflow: {
      title: "GST Filing Flow",
      nodes: [
        { id: "inv", label: "Invoice", sub: "FINALIZED", variant: "start" },
        { id: "irn", label: "IRN", sub: "generated" },
        { id: "gstr1", label: "GSTR-1", sub: "schedule", variant: "active" },
        { id: "itc", label: "ITC Ledger", sub: "reconciled" },
        { id: "gstr3b", label: "GSTR-3B", sub: "filed" },
        { id: "paid", label: "Tax Paid", sub: "challan", variant: "end" },
      ],
    },
    capabilities: [
      { icon: "Receipt", title: "GSTR-1 Auto-Filing", desc: "GSTR-1 register populates from e-invoice schedules — B2B, B2C, exports, credit notes — all classified to the right table. Validate, download JSON, file directly. No spreadsheet exports, no last-minute reconciliation panic." },
      { icon: "FileCheck", title: "GSTR-3B Prep", desc: "GSTR-3B summary builds from your sales and purchase registers with ITC ledger applied. See exactly what cash you'll pay versus credit you'll use, before filing. Pre-flight checks catch mismatches early." },
      { icon: "BookOpen", title: "ITC Ledger", desc: "Track every input tax credit with eligibility status, supplier GSTR-1 match, and reversal triggers (180-day rule, blocked credits, common credit). Real-time visibility into available ITC balance before paying suppliers." },
      { icon: "RefreshCw", title: "RCM Posting", desc: "Auto-detect reverse-charge transactions (unregistered suppliers, specified categories) and post the dual journal — payable and ITC — without manual intervention. GSTR-3B inward supplies under RCM populates from real entries." },
      { icon: "Calculator", title: "TDS / TCS", desc: "Apply correct TDS section based on payee type and transaction nature, generate Form 26Q-ready data, and produce certificates for vendors. TCS Section 206C handled symmetrically for sales side." },
      { icon: "Globe", title: "FEMA Tracking", desc: "Track export proceeds against shipping bills, monitor realization timelines, flag overdue collections, and produce eBRC reconciliation. FEMA Master Directions compliance built into the workflow, not added as an afterthought." },
      { icon: "Wallet", title: "LC Management", desc: "Manage Letter of Credit from issuance through document negotiation, discrepancy resolution, and realization. Tie LCs to specific export shipments; track utilization against issued limits in real time." },
      { icon: "BarChart2", title: "Cost Variance", desc: "Standard vs actual cost variance segmented by grade, machine, and shift. Material, labor, overhead, and FX variances broken out separately so you know exactly where the cost gap is — and can route it to the right person." },
      { icon: "Lock", title: "Period Close", desc: "Soft-close or hard-close each fiscal period with checklist enforcement (bank rec, inventory rec, tax filings done). Once closed, no entries can post back without explicit re-open authorization. Full audit trail every step." },
    ],
    integrations: [
      { module: "Sales", action: "Invoice → AR posting", effect: "Auto-GL receivable + revenue" },
      { module: "Procurement", action: "AP invoice → match", effect: "3-way match before payment" },
      { module: "Inventory", action: "Stock movement → GL", effect: "Auto valuation posting" },
      { module: "Production", action: "WO close → cost settle", effect: "Variance posted to GL" },
      { module: "HR", action: "Payroll → GL journal", effect: "Salary + statutory entries" },
    ],
  },

  hr: {
    slug: "hr",
    tag: "HR & Payroll",
    name: "HR",
    title: "Roster to payroll.",
    highlight: "Statutory by default.",
    blurb: "Multi-shift mill workforce management with gap compliance, bulk attendance, complete Indian statutory payroll (PF, ESI, PT, LWF, TDS, gratuity), Form 16 generation, separation workflow, and ESS/MSS portals.",
    photo: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1920&q=80",
    accent: "#EC4899",
    icon: "Users",
    metrics: [
      { value: "PF+ESI", label: "+ PT/LWF/TDS" },
      { value: "Form 16", label: "auto-gen" },
      { value: "ESS+MSS", label: "self-service" },
      { value: "Gap 2.1", label: "shift compliant" },
    ],
    features: [
      {
        tag: "Workforce Master",
        title: "Employee 360. Privacy gated.",
        body: "Complete employee profiles with education, experience, skills, work history, statutory IDs (PAN, Aadhaar, UAN, PF, ESI), with sensitive PII access gated by RBAC and audit logging.",
        points: [
          "Education, experience, skills, work history",
          "Statutory IDs: PAN, Aadhaar, UAN, PF, ESI",
          "Sensitive PII gates (hr.payroll.view only)",
          "Audit logging per Aadhaar Act §29, IT Act §43A",
          "Direct reports hierarchy",
          "Bulk update for department/designation/manager",
        ],
        photo: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1200&q=80",
      },
      {
        tag: "Shifts & Attendance",
        title: "Multi-shift mills. Gap-compliant.",
        body: "Shift policy and rotating pattern management with Gap 2.1 compliance (11-hour rest enforcement), consecutive night limits, holiday sync, shift change requests, and bulk attendance marking.",
        points: [
          "Shift policy + rotating pattern templates",
          "Gap 2.1 compliance (11-hour rest minimum)",
          "Consecutive night shift limits",
          "Holiday sync between HR + Production",
          "Shift change requests with approval",
          "Bulk attendance marking (CSV)",
          "WFH and late marking support",
        ],
        photo: "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=1200&q=80",
        flip: true,
      },
      {
        tag: "Payroll Processing",
        title: "Salary structures. Statutory at scale.",
        body: "Salary component master, structure assignment per role/grade, CTC preview, payroll processing with PF/ESI/PT/LWF/TDS auto-deduction, gratuity & bonus calculation, arrears, and bank advice file.",
        points: [
          "Salary components: basic, DA, HRA, special, deductions",
          "CTC preview (gross vs. take-home)",
          "PF: 12% of basic+DA, ₹1800 employee cap",
          "ESI: 0.75% employee / 3.25% employer (if gross ≤ ₹21,000)",
          "PT: state-wise slabs (Maharashtra, Karnataka, etc.)",
          "LWF: state-specific Labour Welfare Fund",
          "TDS: annual progressive per IT Act 1961",
          "Arrears + recalc on backdated changes",
          "Bank advice file generation",
        ],
        photo: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80",
      },
      {
        tag: "Statutory Returns",
        title: "ESI. PF. PT. TDS. Form 16. Filed.",
        body: "Generate statutory returns, record challan payments, mark filing status, generate PF Electronic Challan Return (ECR), and produce Form 16 annual TDS certificates.",
        points: [
          "ESI / PF / PT / TDS return generation",
          "Challan recording with payment proof",
          "Mark-as-filed status tracking",
          "PF ECR (Electronic Challan Return) export",
          "Form 16 annual TDS certificate",
          "Statutory registers per Indian Labour Codes",
        ],
        photo: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80",
        flip: true,
      },
      {
        tag: "Leave & Separation",
        title: "Apply. Accrue. Encash. Exit.",
        body: "Configurable leave types with accrual jobs, multi-level approval, LOP tracking, encashment, year-end reset, and complete separation workflow with F&F settlement and clearance.",
        points: [
          "Leave types: PTO, Medical, Casual, etc.",
          "Accrual policies with carryover rules",
          "Multi-level approval with delegation",
          "LOP (Loss of Pay) tracking",
          "Encashment with state-specific rules",
          "Separation: F&F settlement, gratuity, clearance",
          "Investment declaration (80C, 80D)",
        ],
        photo: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1200&q=80",
      },
      {
        tag: "ESS & MSS",
        title: "Self-service. Manager-service.",
        body: "Employee Self-Service for leave, attendance, payslips, expense claims, travel; Manager Self-Service for approvals, team analytics, performance reviews with PII masking.",
        points: [
          "ESS: apply leave, view payslip, expense claims",
          "ESS: WFH request, travel authorization",
          "MSS: leave + attendance approvals",
          "MSS: team payroll (PII masked)",
          "MSS: performance review submission",
          "Bulk email payslips (rate-limited)",
        ],
        photo: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=1200&q=80",
        flip: true,
      },
    ],
    workflow: {
      title: "Payroll Lifecycle",
      nodes: [
        { id: "att", label: "Attendance", sub: "marked", variant: "start" },
        { id: "calc", label: "Calculate", sub: "PF/ESI/TDS" },
        { id: "rev", label: "Review", sub: "preview" },
        { id: "app", label: "Approve", sub: "HR + Finance", variant: "active" },
        { id: "proc", label: "Process", sub: "challans" },
        { id: "pay", label: "Paid", sub: "bank file", variant: "end" },
      ],
    },
    capabilities: [
      { icon: "Clock", title: "Shift Management", desc: "Build rotating shift patterns with Gap 2.1 compliance (11-hour rest minimum), consecutive-night limits, and holiday calendar integration. Roster generation suggests assignments respecting employee preferences and statutory rules." },
      { icon: "ClipboardCheck", title: "Bulk Attendance", desc: "Bulk-mark attendance from CSV or biometric integration. Late/half-day/WFH/leave flags applied per company policy; LOP calculation flows directly into payroll. Saves HR hours every payroll cycle." },
      { icon: "Calculator", title: "PF / ESI / PT / LWF", desc: "Auto-calculate every statutory deduction — PF (12% of basic+DA, ₹1800 cap), ESI (if gross ≤ ₹21K), state-wise PT slabs, LWF per state. Employer contributions tracked separately; rates update per government notifications." },
      { icon: "FileCheck", title: "Form 16", desc: "Annual Form 16 generation per employee with Part A (TDS from Form 24Q) and Part B (salary detail). Bulk-email to employees, with digital signature support. Investment proof reconciliation against declarations." },
      { icon: "BookOpen", title: "PF ECR", desc: "Generate PF Electronic Challan Return file in EPFO's exact format. Validate against UAN universe before submission; track challan payment and filing status from one dashboard. No more failed uploads to the PF portal." },
      { icon: "Calendar", title: "Leave Accrual", desc: "Configure leave types (CL, SL, PL, comp-off) with monthly or annual accrual rates, carry-forward caps, and encashment rules. Year-end reset runs automatically; balance visible to employees in ESS." },
      { icon: "Award", title: "Performance Reviews", desc: "Run appraisal cycles with self-review, manager-review, and peer feedback (360°). Competency ratings against the job's matrix; goal achievement tracked against quarterly OKRs. Outputs feed bonus + promotion decisions." },
      { icon: "Lock", title: "PII Gated Access", desc: "Aadhaar, PAN, salary, and bank account fields are gated by specific RBAC permissions and every access is audit-logged (per Aadhaar Act §29 and IT Act §43A). View-without-need triggers alerts to compliance team." },
      { icon: "Users", title: "ESS / MSS", desc: "Employee Self-Service for applying leave, viewing payslips, submitting expenses, declaring investments. Manager Self-Service for approvals, team attendance, payroll visibility (masked PII), and review submission." },
    ],
    integrations: [
      { module: "Production", action: "Shift assignment → shop floor", effect: "Sync with WO labor entries" },
      { module: "Production", action: "Labor entry → cost", effect: "Pull employee rates per role" },
      { module: "Finance", action: "Payroll process → GL journal", effect: "Salary + statutory entries" },
      { module: "Finance", action: "TDS → tax ledger", effect: "Auto TDS payable posting" },
      { module: "Approvals", action: "Leave/expense → matrix", effect: "Route by manager hierarchy" },
    ],
  },

  ai: {
    slug: "ai",
    tag: "AI & Analytics",
    name: "AI",
    title: "Ask your ERP anything.",
    highlight: "Act instantly.",
    blurb: "Natural language chat across all 44 modules, AI-powered bulk actions with human-in-the-loop preview, 50+ predictive analytics (cash flow, demand forecasting, anomaly detection), and a 5-phase analytics roadmap.",
    photo: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?auto=format&fit=crop&w=1920&q=80",
    accent: "#A78BFA",
    icon: "Sparkles",
    metrics: [
      { value: "50+", label: "AI insights" },
      { value: "5", label: "phases" },
      { value: "20/min", label: "rate-limited" },
      { value: "Multi-LLM", label: "configurable" },
    ],
    features: [
      {
        tag: "Conversational AI",
        title: "Plain English. Real answers.",
        body: "Context-aware chat assistant with conversation persistence, token budget management, streaming responses, multi-language support (EN, HI, TA), and full audit history.",
        points: [
          "Context-aware multi-turn conversations",
          "Conversation persistence + history search",
          "Token budget management + cost control",
          "Streaming responses for low-latency UX",
          "Multi-language: English, Hindi, Tamil",
          "Rate-limited (20 req/min) with quota enforcement",
        ],
        photo: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=1200&q=80",
      },
      {
        tag: "Bulk Actions",
        title: "AI assists. Humans approve.",
        body: "AI-powered bulk operations across modules — auto-approve low-risk POs, bulk attendance from biometric data, smart batch allocation — with mandatory human preview before execution.",
        points: [
          "50+ pre-configured bulk action workflows",
          "Human-in-the-loop preview before execution",
          "Max 50 items per bulk action (safety)",
          "Full audit trail per bulk run",
          "Action registry with permission gates",
          "Smart form auto-fill with context",
        ],
        photo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
        flip: true,
      },
      {
        tag: "Predictive Analytics (5 Phases)",
        title: "50+ predictions. Production-ready.",
        body: "Phase 1: ABC/XYZ analysis, dead stock, anomaly detection. Phase 2: cash flow, demand forecasting, churn, OEE. Phase 3: document intelligence, quality predictions. Phase 4: maintenance, energy. Phase 5: digital twin, supply chain control tower.",
        points: [
          "Phase 1: ABC/XYZ, dead stock, anomaly detection",
          "Phase 2: cash flow + demand forecasting",
          "Phase 2: payment behavior + credit risk scoring",
          "Phase 3: document intelligence + quality predictions",
          "Phase 4: predictive maintenance + energy",
          "Phase 5: digital twin + supply chain control tower",
        ],
        photo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80",
      },
    ],
    workflow: {
      title: "AI Chat-to-Action Flow",
      nodes: [
        { id: "q", label: "User Query", sub: "natural lang", variant: "start" },
        { id: "ctx", label: "Context", sub: "module APIs" },
        { id: "llm", label: "LLM", sub: "reasoning", variant: "active" },
        { id: "ans", label: "Answer", sub: "with sources" },
        { id: "act", label: "Suggest Action", sub: "preview" },
        { id: "exec", label: "Execute", sub: "audit log", variant: "end" },
      ],
    },
    capabilities: [
      { icon: "MessageSquare", title: "Conversational Chat", desc: "Multi-turn natural language conversations that remember context across turns. Ask follow-ups without re-stating; the assistant tracks your line of inquiry and offers relevant drill-downs. Available in English, Hindi, and Tamil." },
      { icon: "Search", title: "Cross-module Query", desc: "Ask questions that span modules — 'why did GlobalPrint's revenue drop?' pulls sales orders, dispatch delays, and finance data simultaneously. The answer cites its sources so you can verify and drill in." },
      { icon: "Zap", title: "Bulk Actions", desc: "Approve POs, mark attendance, allocate batches, or close work orders in bulk with AI selecting low-risk candidates. Human-in-the-loop preview before execution; every bulk run audit-logged per item. Up to 50 items per batch." },
      { icon: "Brain", title: "50+ Predictions", desc: "Production-ready predictive models across 5 phases — demand forecasting, churn risk, payment behavior, OEE projections, predictive maintenance, energy use, supply chain control tower. New models added each release." },
      { icon: "ShieldCheck", title: "Audit-safe", desc: "Full conversation history with prompt, response, and any actions taken. Compliance teams can replay any chat session; data access from chat respects user RBAC; no permission elevation through AI." },
      { icon: "Activity", title: "Anomaly Detection", desc: "Statistical and ML anomaly detection on invoices, approvals, process flows, and finance entries. Surfaces things humans miss — duplicate vendor entries, irregular approval patterns, transactions outside normal range." },
      { icon: "TrendingUp", title: "Demand Forecasting", desc: "ML-based demand forecasting per product/customer with seasonality, trend, and external signals (mill capacity, holidays). Feeds MPS directly; planners see suggested production volumes with confidence intervals." },
      { icon: "Eye", title: "Document Intelligence", desc: "OCR + AI-classification on inbound invoices, POs, and certificates. Extracts vendor, amount, GSTIN, line items with confidence scores; auto-attaches to matching transaction. Eliminates manual document entry." },
      { icon: "Cog", title: "Workflow Guides", desc: "AI suggests the next best action based on context — 'this customer's credit is at 85%, suggest sending the dunning email,' or 'this PO is from a new vendor, suggest running KYC checks first.' Speeds onboarding for new users." },
    ],
    integrations: [
      { module: "All Modules", action: "AI query → data fetch", effect: "Pulls live data via internal APIs" },
      { module: "Approvals", action: "AI suggest → human approve", effect: "Bulk approval with preview" },
      { module: "Sales", action: "Forecast → demand", effect: "Predictive ordering" },
      { module: "Inventory", action: "ABC/XYZ → reorder", effect: "Automatic reorder triggers" },
      { module: "Finance", action: "Cash flow → forecast", effect: "Predictive payment behavior" },
    ],
  },

  party: {
    slug: "party",
    tag: "Party Management",
    name: "Party",
    title: "Customers. Suppliers.",
    highlight: "360° profiles. Compliant.",
    blurb: "Master data for 11 party types — customers, suppliers, transporters, banks, agents, brokers — with multi-address, multi-contact, multi-bank, certifications with expiry alerts, credit terms, MSME registration, and bulk import.",
    photo: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=1920&q=80",
    accent: "#64748B",
    icon: "Building2",
    metrics: [
      { value: "11", label: "party types" },
      { value: "5", label: "status states" },
      { value: "MSME", label: "Udyam validation" },
      { value: "Bulk", label: "CSV import" },
    ],
    features: [
      {
        tag: "Hierarchical Profiles",
        title: "One party. Many facets.",
        body: "11 party types with 5 status states, multiple addresses (Billing, Shipping, Registered, Branch, Warehouse, Factory), role-based contacts, bank accounts with NEFT/RTGS support, tax information, and group relationships.",
        points: [
          "11 party types: customer, supplier, transporter, bank, etc.",
          "5 status states with workflow",
          "Multiple addresses with role tagging",
          "Role-based contacts (Primary, Billing, Tech, Quality, etc.)",
          "Bank accounts with IBAN/SWIFT for exports",
          "Multi-jurisdiction tax info",
          "Parent/child group relationships",
        ],
        photo: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1200&q=80",
      },
      {
        tag: "Credit & Risk",
        title: "Limits. Exposure. Risk-rated.",
        body: "Configurable credit limits with utilization tracking, payment terms with early-payment discounts, delivery preferences, territory auto-assignment, risk rating (Low to Critical), and blacklist management.",
        points: [
          "Credit limit with real-time utilization",
          "Payment terms with early-payment discounts",
          "Risk rating: Low, Medium, High, Critical",
          "Territory auto-assignment by region",
          "Blacklist with reason tracking",
          "Delivery preferences and rules",
        ],
        photo: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1200&q=80",
        flip: true,
      },
      {
        tag: "Documents & Certifications",
        title: "PAN. GSTIN. ISO. Expiry-alerted.",
        body: "Secure document upload with versioning, certification tracking with expiry alerts (ISO 9001, food safety, etc.), role-based access control, and audit logging for sensitive data.",
        points: [
          "PAN, GSTIN, IEC, bank proofs upload",
          "ISO 9001, FSSAI, OHSAS certifications",
          "Expiry alerts before lapse",
          "Role-based document access",
          "Audit log per document view",
          "Version control + download history",
        ],
        photo: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80",
      },
      {
        tag: "Bulk Operations",
        title: "Import thousands. Deduplicate. Validate.",
        body: "CSV template download, validation before import, duplicate detection (hard by GSTIN, soft by name), bulk party onboarding with error reporting, and party code auto-generation.",
        points: [
          "CSV template with field validation",
          "Hard dedup by GSTIN",
          "Soft dedup by name (configurable)",
          "Bulk import with per-row error reporting",
          "Party code auto-generation",
          "Status bulk updates",
        ],
        photo: "https://images.unsplash.com/photo-1606857521015-7f9fcf423740?auto=format&fit=crop&w=1200&q=80",
        flip: true,
      },
    ],
    workflow: {
      title: "Party Onboarding Flow",
      nodes: [
        { id: "create", label: "Create", sub: "manual or CSV", variant: "start" },
        { id: "validate", label: "Validate", sub: "GSTIN + PAN" },
        { id: "dedup", label: "Dedup Check", sub: "hard + soft" },
        { id: "docs", label: "Documents", sub: "PAN/GST/ISO" },
        { id: "approve", label: "Approve", sub: "workflow", variant: "active" },
        { id: "active", label: "Active", sub: "transactable", variant: "end" },
      ],
    },
    capabilities: [
      { icon: "Users", title: "11 Party Types", desc: "Single master for customers, suppliers, transporters, banks, agents, brokers, employees, government bodies, consultants, contractors, and other. One party can play multiple roles; the right context activates per transaction." },
      { icon: "MapPin", title: "Multi-address", desc: "Capture billing, shipping, registered, factory, warehouse, and branch addresses for any party with role-based selection. Sales picks shipping; finance picks billing — no more wrong addresses on invoices or dispatches." },
      { icon: "Wallet", title: "Multi-bank Accounts", desc: "Multiple bank accounts per party with NEFT/RTGS/IMPS routing details for domestic and IBAN/SWIFT for exports. Payment runs auto-pick the right account; bounce-handling tracks per-account history." },
      { icon: "Calendar", title: "Expiry Alerts", desc: "Track validity of ISO 9001, FSSAI, OHSAS, ESG, and any custom certification per party. Configurable alert windows (30/60/90 days before expiry); critical for supplier audits and customer KYC requirements." },
      { icon: "Shield", title: "MSME / Udyam", desc: "Capture Udyam registration number, classify suppliers as micro/small/medium. Triggers 45-day payment window enforcement and Section 43B(h) compliance. Avoid tax disallowance through proactive payment scheduling." },
      { icon: "AlertCircle", title: "Risk Ratings", desc: "Rate parties Low / Medium / High / Critical based on credit history, payment behavior, compliance issues, or country risk. Risk rating gates transaction limits and triggers additional approval levels automatically." },
      { icon: "FilePlus", title: "Bulk CSV Import", desc: "Import thousands of parties from CSV with hard dedup by GSTIN (blocks duplicates) and soft dedup by name (flags for review). Per-row validation; failed rows downloaded with error explanation for re-upload." },
      { icon: "Lock", title: "Doc Access Control", desc: "Sensitive documents (PAN, GSTIN, bank proofs, contracts) gated by RBAC permissions. Every view and download audit-logged; documents marked confidential require additional approval to access." },
      { icon: "Bell", title: "Blacklist Tracking", desc: "Blacklist a party with reason category (fraud, non-payment, quality issues, legal) and full audit trail. Blacklisted parties can't transact; bulk import checks against blacklist; reactivation requires senior approval." },
    ],
    integrations: [
      { module: "Sales", action: "Order create → party lookup", effect: "Pull credit + payment terms" },
      { module: "Procurement", action: "Supplier select → MSME check", effect: "Apply 45-day payment rule" },
      { module: "Finance", action: "Invoice → party tax info", effect: "Apply GSTIN + TDS section" },
      { module: "AI", action: "Lead scoring → party stats", effect: "Use historical conversion data" },
    ],
  },
};

export const MODULE_SLUGS = Object.keys(MODULES_DATA);
