import { ModuleData } from "./data";

export const EXTRA_MODULES: Record<string, ModuleData> = {
  "stock-preparation": {
    slug: "stock-preparation", tag: "Stock Preparation", name: "Stock Prep",
    title: "Pulp to paper machine.", highlight: "Chemistry controlled.",
    blurb: "Manage pulping, refining, blending, chemical dosing, chest level control, consistency, and stuff prep — the critical upstream operation that determines paper quality before it ever hits the wire.",
    photo: "https://images.unsplash.com/photo-1581094271901-8022df4466f9?auto=format&fit=crop&w=1920&q=80",
    accent: "#0D9488", icon: "Workflow",
    metrics: [{ value: "Multi-furnish", label: "blending" }, { value: "Live", label: "consistency" }, { value: "Chemistry", label: "dosing" }, { value: "Chest", label: "level control" }],
    features: [
      { tag: "Pulp Furnish", title: "Blend recipes per grade.", body: "Define furnish ratios per paper grade — virgin + recycled + broke + chemicals. Pulp specifications (freeness, fiber length, brightness) tracked at each stage.", points: ["Per-grade furnish recipes", "Multi-pulp blending with target ratios", "Freeness + fiber length tracking", "Recycled fiber inclusion limits", "Broke re-pulping integration", "Chemistry cost per grade"], photo: "https://images.unsplash.com/photo-1581094271901-8022df4466f9?auto=format&fit=crop&w=1200&q=80" },
      { tag: "Chemical Dosing", title: "Sizing, retention, drainage.", body: "Configure and track chemical dosing — sizing agents, retention aids, drainage aids, wet/dry strength additives, dyes. Targets per grade, actuals per shift, variance flagged.", points: ["Chemical master with usage targets", "Per-machine dosing setpoints", "Shift-wise consumption tracking", "Cost-per-tonne by chemical", "Variance alerts on overdose", "Inventory deduction on consumption"], photo: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1200&q=80", flip: true },
      { tag: "Chest & Consistency", title: "Levels, flows, stocks.", body: "Live monitoring of machine chest levels, blend chest flows, stuff box consistency. SCADA integration for real-time tank levels; alerts when limits approached.", points: ["Live chest level dashboards", "Flow tracking with SCADA feed", "Consistency setpoints + alerts", "Stuff box management", "Auto-block production on out-of-spec", "Historical trends per machine"], photo: "https://images.unsplash.com/photo-1581094271901-8022df4466f9?auto=format&fit=crop&w=1200&q=80" },
    ],
    workflow: { title: "Stock Prep Flow", nodes: [{ id: "furnish", label: "Furnish", sub: "blend", variant: "start" }, { id: "refine", label: "Refine", sub: "freeness" }, { id: "chem", label: "Chemistry", sub: "dose", variant: "active" }, { id: "chest", label: "Chest", sub: "level" }, { id: "wire", label: "To Wire", sub: "consistency", variant: "end" }] },
    capabilities: [
      { icon: "Workflow", title: "Furnish Recipes", desc: "Per-grade furnish ratios with virgin pulp, recycled fiber, broke, and chemicals. Recipes versioned, approved, and locked into production runs." },
      { icon: "Calculator", title: "Dosing Calculator", desc: "Real-time chemical dosing calculation based on production rate, grade, and target setpoints. Live consumption logged against actuals." },
      { icon: "Activity", title: "Live Consistency", desc: "Stuff consistency monitored live from machine chest sensors. Out-of-spec triggers operator alert and auto-blocks paper machine acceptance." },
      { icon: "Database", title: "Chemical Master", desc: "Centralized chemical master with safety data sheets, usage limits, costs, and supplier mappings." },
      { icon: "BarChart2", title: "Yield Tracking", desc: "Pulp-to-paper yield calculated per shift and per grade. Variance from target investigated and root-caused." },
      { icon: "RefreshCw", title: "Broke Re-pulping", desc: "Broke material auto-routed back into furnish per grade-specific rules. Maintains material balance." },
      { icon: "AlertCircle", title: "Out-of-Spec Alerts", desc: "Freeness, consistency, brightness, ash content — all monitored. Out-of-spec runs flagged and trace to root cause in Stock Prep." },
      { icon: "Cog", title: "SCADA Integration", desc: "Live tank levels, flows, motor loads pulled from SCADA. No manual data entry; alerts at source." },
      { icon: "Receipt", title: "Cost per Tonne", desc: "Material + chemistry cost per tonne calculated live. Engine flags grades drifting above target cost." },
    ],
    integrations: [
      { module: "Production", action: "Furnish ready → WO", effect: "Paper machine pulls when chest is in-spec" },
      { module: "Inventory", action: "Chemical consumption → stock", effect: "Auto-deduct on dose" },
      { module: "Quality", action: "Pulp QC → spec match", effect: "Block if furnish out-of-spec" },
      { module: "IoT", action: "SCADA → live data", effect: "Tank levels + flows from sensors" },
    ],
  },

  "converting-finishing": {
    slug: "converting-finishing", tag: "Converting & Finishing", name: "Converting",
    title: "Reel to ream.", highlight: "Every cut tracked.",
    blurb: "Reel slitting, sheet cutting, ream packing, carton management, and finishing operations — the downstream value-add steps that turn jumbo reels into ready-to-ship customer SKUs.",
    photo: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1920&q=80",
    accent: "#FB923C", icon: "Scissors",
    metrics: [{ value: "Reel→Ream", label: "tracked" }, { value: "Slitting", label: "+ sheeting" }, { value: "Pack", label: "automation" }, { value: "Yield", label: "analytics" }],
    features: [
      { tag: "Slitting & Sheeting", title: "Reel → customer widths.", body: "Convert mother reels into customer-width reels or sheets per dispatch plan. Pattern from Deckle Optimizer; execution + yield tracking here.", points: ["Reel-to-reel slitting", "Reel-to-sheet cutting (cutter)", "Pattern execution from Deckle plans", "Slit yield tracking", "Trim weight reconciliation", "Customer width assignment"], photo: "https://images.unsplash.com/photo-1517420704952-d9f39e95b43e?auto=format&fit=crop&w=1200&q=80" },
      { tag: "Ream & Packaging", title: "Wrap, palletize, label.", body: "Ream packing with sheet counts, customer-specific wrapping, barcode labels per ream, palletization, shrink-wrap. Per-SKU pack rules.", points: ["Ream sheet-count configurations", "Per-customer pack specifications", "Barcode labels per ream", "Pallet pattern optimization", "Shrink-wrap + carton ops", "Per-pallet weight verification"], photo: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?auto=format&fit=crop&w=1200&q=80", flip: true },
      { tag: "Finishing Lines", title: "Coating, calendering, embossing.", body: "Manage finishing operations beyond converting — coating lines, supercalenders, embossers, special treatments. Recipe-driven, quality-gated.", points: ["Coating recipe management", "Calendering pressure setpoints", "Embossing pattern library", "Lacquering / varnishing", "Quality gate per finish", "Finish-specific tolerances"], photo: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1200&q=80" },
    ],
    workflow: { title: "Converting Flow", nodes: [{ id: "reel", label: "Mother Reel", sub: "input", variant: "start" }, { id: "slit", label: "Slit", sub: "Deckle plan" }, { id: "cut", label: "Cut", sub: "to size", variant: "active" }, { id: "pack", label: "Pack", sub: "+ label" }, { id: "ship", label: "Ready", sub: "to ship", variant: "end" }] },
    capabilities: [
      { icon: "Scissors", title: "Slitter Execution", desc: "Execute slitting plans from Deckle Optimizer on the winder. Real-time yield + trim tracking; mother-reel consumption logged." },
      { icon: "Layers", title: "Sheet Cutting", desc: "Cross-cut reels into sheets via rotary or stationary cutters. Sheet count + dimensions per customer spec; trim reconciled." },
      { icon: "Package", title: "Ream Packing", desc: "Configurable ream sizes (250/500/1000 sheets), wrapping types, label formats per customer. Automated workflows minimize errors." },
      { icon: "ScanLine", title: "Per-ream Barcode", desc: "Auto-printed barcode labels per ream with batch, GSM, grade, customer reference. Scanned at dispatch for verification." },
      { icon: "Boxes", title: "Pallet Optimization", desc: "Optimize pallet patterns for transport stability and load. Per-customer pallet height/weight limits." },
      { icon: "Award", title: "Finishing Recipes", desc: "Per-grade finishing recipes — coating thickness, calendering pressure, embossing patterns. Versioned and approved." },
      { icon: "ClipboardCheck", title: "Per-stage QC", desc: "Quality gates after slitting, after finishing, after packing. Failure traps the batch before it ships." },
      { icon: "BarChart2", title: "Yield Analytics", desc: "Reel-to-saleable yield per shift, per grade, per cutter. Identify yield-loss sources for continuous improvement." },
      { icon: "Truck", title: "Dispatch Ready", desc: "Converting output flows directly into dispatch — no manual hand-off, no double-entry, no waiting." },
    ],
    integrations: [
      { module: "Deckle Optimizer", action: "Slit plan → execute", effect: "Pattern executed on winder" },
      { module: "Inventory", action: "Slit reels → FG stock", effect: "Auto-batch creation" },
      { module: "Sales", action: "Customer allocation → packing", effect: "Order-specific pack specs" },
      { module: "Quality", action: "Post-converting QC", effect: "Per-stage acceptance" },
    ],
  },

  "broke-management": {
    slug: "broke-management", tag: "Broke Management", name: "Broke Mgmt",
    title: "Every broke kilogram.", highlight: "Classified. Recovered.",
    blurb: "Promoted from sub-feature to dedicated module — broke (paper waste) tracking, classification, root-cause analysis, repulping recovery, and Pareto analytics to systematically reduce waste at every stage.",
    photo: "https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=1920&q=80",
    accent: "#DC2626", icon: "RefreshCw",
    metrics: [{ value: "Per-source", label: "tracking" }, { value: "Pareto", label: "analytics" }, { value: "Recovery", label: "tracked" }, { value: "Target", label: "per grade" }],
    features: [
      { tag: "Broke Capture", title: "Where, why, how much.", body: "Log every broke event with source (wet-end, dry-end, calender, winder, converting), grade, weight, reason. Capture happens at point-of-occurrence via shop floor or mobile.", points: ["Capture at point of occurrence", "Mobile-enabled shop floor entry", "Source + grade + reason classification", "Per-shift, per-machine tracking", "Photo evidence support", "Auto-link to producing work order"], photo: "https://images.unsplash.com/photo-1565793298495-4f3c61ee7ec1?auto=format&fit=crop&w=1200&q=80" },
      { tag: "Repulping & Recovery", title: "Waste back into furnish.", body: "Track repulping operations — broke routed back into pulp prep, recovery percentage per type, recipe-specific re-blending rules.", points: ["Repulping batch tracking", "Recovery % per broke type", "Grade-specific re-blend rules", "Material balance reconciliation", "Cost recovery vs disposal", "Inventory tracking for broke stock"], photo: "https://images.unsplash.com/photo-1581094271901-8022df4466f9?auto=format&fit=crop&w=1200&q=80", flip: true },
      { tag: "Pareto Analytics", title: "Find the 20% causing 80%.", body: "Pareto charts by source, grade, shift, machine, root cause. Surface the top broke contributors so improvement projects target the right problems.", points: ["Multi-dimensional Pareto charts", "Trend over weeks/months", "Drill-down to root cause", "Cost impact per source", "Comparative analysis (shift A vs B)", "Auto-flag emerging patterns"], photo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80" },
    ],
    workflow: { title: "Broke Lifecycle", nodes: [{ id: "occur", label: "Occur", sub: "shop floor", variant: "start" }, { id: "log", label: "Log", sub: "+ classify" }, { id: "weigh", label: "Weigh", sub: "+ track" }, { id: "route", label: "Route", sub: "to repulper", variant: "active" }, { id: "recover", label: "Recover", sub: "% tracked" }, { id: "analyze", label: "Analyze", sub: "Pareto", variant: "end" }] },
    capabilities: [
      { icon: "RefreshCw", title: "Point-of-Occurrence Capture", desc: "Log broke the moment it happens — via shop floor terminal, mobile app, or operator entry. No batch-end reconciliation surprises." },
      { icon: "Layers", title: "Source Classification", desc: "Pre-defined sources: wet-end, dry-end, calender, slitter, winder, converting, off-spec, off-grade. Drives root-cause analytics." },
      { icon: "Calculator", title: "Recovery % per Type", desc: "Different broke types have different recovery characteristics. Track recovery rate per type to optimize repulping mix." },
      { icon: "BarChart2", title: "Pareto Analytics", desc: "Multi-dimensional Pareto — by source, grade, shift, machine, root cause. Find your 20% that causes 80% of waste." },
      { icon: "Target", title: "Per-Grade Targets", desc: "Configurable broke targets per grade and machine. Variance flagged automatically; teams accountable for hitting targets." },
      { icon: "TrendingDown", title: "Trend Analysis", desc: "Week-over-week, month-over-month broke trends. Identify whether improvement projects are actually working." },
      { icon: "AlertCircle", title: "Emerging Pattern Detection", desc: "ML watches for emerging patterns — sudden spike in specific source/grade combo flags before it becomes systemic." },
      { icon: "Receipt", title: "Cost Impact", desc: "Translate kilos to rupees. Broke cost per source = material + conversion + recovery loss. Makes the business case clear." },
      { icon: "Smartphone", title: "Mobile Capture", desc: "Operators log broke from mobile at the source. Photos attached for visual evidence; works offline with sync." },
    ],
    integrations: [
      { module: "Production", action: "WO completion → broke %", effect: "Per-WO broke vs target" },
      { module: "Stock Prep", action: "Broke → repulper", effect: "Re-blend into furnish" },
      { module: "Inventory", action: "Broke stock tracked", effect: "Pre-repulp inventory visibility" },
      { module: "Finance", action: "Broke cost → GL", effect: "Variance posted to grade cost" },
    ],
  },

  "recipe-development": {
    slug: "recipe-development", tag: "Recipe Development & R&D", name: "Recipe Dev",
    title: "New grades. Tested.", highlight: "Proven. Released.",
    blurb: "Paper grade recipe library with trial management, version control, test batches, customer approval workflow, and commercial release. The R&D-to-production pipeline for new product introductions.",
    photo: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1920&q=80",
    accent: "#9333EA", icon: "FlaskConical",
    metrics: [{ value: "Trial", label: "management" }, { value: "Versioned", label: "recipes" }, { value: "Patent", label: "tracking" }, { value: "Approval", label: "workflow" }],
    features: [
      { tag: "Recipe Library", title: "Every formulation. Cataloged.", body: "Central recipe library with furnish ratios, chemistry, machine setpoints, target quality parameters. Searchable by grade family, customer, performance.", points: ["Per-grade complete recipe", "Furnish + chemistry + setpoints", "Target quality parameters", "Version history with diff", "Patent / IP marking", "Search by performance criteria"], photo: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?auto=format&fit=crop&w=1200&q=80" },
      { tag: "Trial Management", title: "Test before commercial.", body: "Run controlled trials of new recipes — schedule trial slots, capture results, compare against targets, iterate. Statistical confidence before commercial release.", points: ["Trial scheduling on production windows", "Result capture vs hypothesis", "Statistical confidence calculation", "Iteration tracking", "Customer sample workflow", "Trial-to-commercial promotion"], photo: "https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&w=1200&q=80", flip: true },
      { tag: "Customer Approval", title: "Pilot, sample, sign off.", body: "Send trial output as samples to customers. Capture customer feedback, approval status, suggested adjustments. Sign-off before commercial production.", points: ["Customer sample dispatch tracking", "Per-customer feedback capture", "Approval status workflow", "Suggested adjustment log", "Sign-off documentation", "Auto-create commercial product on approval"], photo: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80" },
    ],
    workflow: { title: "Recipe Lifecycle", nodes: [{ id: "concept", label: "Concept", sub: "R&D", variant: "start" }, { id: "lab", label: "Lab Trial", sub: "small scale" }, { id: "mill", label: "Mill Trial", sub: "production", variant: "active" }, { id: "sample", label: "Customer Sample", sub: "feedback" }, { id: "approve", label: "Approve", sub: "sign off" }, { id: "commercial", label: "Commercial", sub: "released", variant: "end" }] },
    capabilities: [
      { icon: "FlaskConical", title: "Recipe Library", desc: "Central library of every paper grade recipe — furnish, chemistry, setpoints, quality targets. Searchable and version-controlled." },
      { icon: "GitBranch", title: "Version Control", desc: "Every recipe edit creates a new version with diff. Roll back if a change degrades performance; see complete change history." },
      { icon: "ClipboardList", title: "Trial Scheduling", desc: "Schedule trials in production windows without disrupting commercial runs. Trial-specific machine setup and quality criteria." },
      { icon: "BarChart2", title: "Statistical Analysis", desc: "Per-trial statistical analysis — mean, variance, confidence intervals on quality parameters. Decide on commercial release with data." },
      { icon: "RefreshCw", title: "Iteration Tracking", desc: "Recipe iterations linked as a chain. See how a recipe evolved from concept through commercial release." },
      { icon: "Award", title: "Customer Samples", desc: "Dispatch pre-commercial samples to customers. Track feedback per customer; aggregate for go/no-go decision." },
      { icon: "FileCheck", title: "Approval Sign-off", desc: "Multi-tier approval workflow — R&D head, plant head, customer (if applicable), commercial team. Documented sign-off." },
      { icon: "Shield", title: "Patent / IP", desc: "Mark proprietary recipes as patent-pending or trade-secret. RBAC-gate access; audit every view." },
      { icon: "Search", title: "Performance Search", desc: "Search recipes by target performance — 'find a recipe with brightness >85 and burst >180'. Re-use proven formulations." },
    ],
    integrations: [
      { module: "Production", action: "Recipe → WO setup", effect: "Auto-populate machine setpoints" },
      { module: "Quality", action: "Trial results → recipe", effect: "Feed back into iteration" },
      { module: "Sales", action: "Customer approval → SKU", effect: "Create sellable product" },
      { module: "Stock Prep", action: "Recipe → furnish", effect: "Trial-specific blends" },
    ],
  },

  crm: {
    slug: "crm", tag: "Customer Relationship Management", name: "CRM",
    title: "Every customer.", highlight: "Every touchpoint.",
    blurb: "Sales pipeline, opportunity tracking, account management, contact management, activity logging, win-loss analysis. The customer-360 hub that sales reps live in.",
    photo: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1920&q=80",
    accent: "#06B6D4", icon: "Users",
    metrics: [{ value: "360°", label: "customer view" }, { value: "Pipeline", label: "tracked" }, { value: "Activity", label: "logged" }, { value: "Win-loss", label: "analyzed" }],
    features: [
      { tag: "Pipeline Management", title: "Every opportunity. Every stage.", body: "Visual sales pipeline with stages (Lead → Qualified → Proposal → Negotiation → Won/Lost). Drag-drop progression; weighted forecast; per-rep targets.", points: ["Visual Kanban pipeline", "Customizable stages per business", "Weighted revenue forecast", "Per-rep + per-territory targets", "Forecast accuracy tracking", "Stalled-deal alerts"], photo: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80" },
      { tag: "Activity Logging", title: "Calls, emails, visits, samples.", body: "Log every customer interaction — calls, emails, on-site visits, sample dispatches, complaint resolution. Complete customer history in one timeline.", points: ["Calls, emails, meetings logged", "Sample dispatch tracking", "Complaint history", "Email integration with auto-log", "Mobile log-on-the-go", "Per-rep activity dashboard"], photo: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1200&q=80", flip: true },
      { tag: "Account 360", title: "One screen. Everything.", body: "Single screen view of customer — orders, invoices, payments, complaints, samples, contacts, credit, activity history. No more 'let me find that file'.", points: ["Order + invoice + payment history", "Complaints + resolutions", "Sample dispatch history", "Multi-contact per account", "Credit + payment behavior", "Activity timeline"], photo: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1200&q=80" },
    ],
    workflow: { title: "Pipeline Flow", nodes: [{ id: "lead", label: "Lead", sub: "captured", variant: "start" }, { id: "qual", label: "Qualified", sub: "fit + budget" }, { id: "prop", label: "Proposal", sub: "quote sent", variant: "active" }, { id: "neg", label: "Negotiation", sub: "iterate" }, { id: "close", label: "Won / Lost", sub: "loss reason", variant: "end" }] },
    capabilities: [
      { icon: "Users", title: "Account 360", desc: "One screen for every customer — orders, invoices, payments, complaints, samples, contacts, credit. Eliminates the 'where is that?' problem." },
      { icon: "Workflow", title: "Pipeline Kanban", desc: "Visual pipeline by stage with drag-drop progression. Weighted forecast roll-up to manager and director dashboards." },
      { icon: "Calendar", title: "Activity Timeline", desc: "Every call, email, visit, sample, and complaint on a single timeline. Hand-offs between reps preserve context completely." },
      { icon: "TrendingUp", title: "Forecast Accuracy", desc: "Forecast vs actual tracked over time. Rep-level forecast accuracy improves coaching and capacity planning." },
      { icon: "Target", title: "Per-Rep Targets", desc: "Quarterly + annual targets per rep, per territory, per product family. Real-time achievement tracking." },
      { icon: "AlertCircle", title: "Stalled Deal Alerts", desc: "Deals sitting in same stage too long flagged automatically. Manager dashboards surface attention items." },
      { icon: "Award", title: "Win-Loss Analysis", desc: "Every lost deal captures loss reason. Win-loss reports surface competitive weak spots and pricing issues." },
      { icon: "Smartphone", title: "Mobile CRM", desc: "Field reps log activity, look up account, send quotes from mobile. Works offline; syncs back to the central pipeline." },
      { icon: "Mail", title: "Email Integration", desc: "Outlook / Gmail integration auto-logs customer emails against the right account. No more manual logging." },
    ],
    integrations: [
      { module: "Sales", action: "Won deal → SO", effect: "Auto-create sales order" },
      { module: "Party", action: "Account master sync", effect: "Single customer record" },
      { module: "Email Hub", action: "Email log → activity", effect: "Auto-track communications" },
      { module: "AI", action: "Lead scoring", effect: "Prioritize hot leads" },
    ],
  },

  helpdesk: {
    slug: "helpdesk", tag: "Customer Service & Helpdesk", name: "Helpdesk",
    title: "Tickets in.", highlight: "Resolution out.",
    blurb: "Ticket-based customer support with SLA tracking, knowledge base, customer portal, satisfaction surveys. Complaint resolution that closes the loop instead of letting issues fester.",
    photo: "https://images.unsplash.com/photo-1556745757-8d76bdb6984b?auto=format&fit=crop&w=1920&q=80",
    accent: "#F59E0B", icon: "MessageSquare",
    metrics: [{ value: "SLA", label: "tracked" }, { value: "Multi-channel", label: "intake" }, { value: "KB", label: "self-service" }, { value: "CSAT", label: "surveyed" }],
    features: [
      { tag: "Ticket Management", title: "Capture. Route. Resolve.", body: "Tickets from email, phone, customer portal, or chat — all into one queue. Auto-route by category, priority, customer importance. SLA timers on every ticket.", points: ["Multi-channel intake (email/phone/portal/chat)", "Auto-categorization by AI", "Priority + SLA assignment", "Auto-route to right team", "Escalation on SLA breach", "Resolution tracking"], photo: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1200&q=80" },
      { tag: "Knowledge Base", title: "Self-service first.", body: "Searchable knowledge base of common questions, troubleshooting guides, product docs. Customers self-serve; ticket volume drops.", points: ["Searchable KB articles", "Per-product organization", "AI-suggested articles on ticket creation", "Customer self-service portal", "Article effectiveness metrics", "Multi-language support"], photo: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80", flip: true },
      { tag: "Customer Portal", title: "Customers track. Themselves.", body: "Customer-facing portal — submit tickets, track status, view history, access knowledge base, download documents. Reduces support call volume.", points: ["Branded customer portal", "Ticket submission + tracking", "Order + invoice access", "Document download", "Self-service KB", "Mobile-responsive"], photo: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1200&q=80" },
    ],
    workflow: { title: "Ticket Flow", nodes: [{ id: "create", label: "Create", sub: "any channel", variant: "start" }, { id: "categ", label: "Categorize", sub: "AI-assisted" }, { id: "route", label: "Route", sub: "to team", variant: "active" }, { id: "work", label: "Work", sub: "SLA tracked" }, { id: "resolve", label: "Resolve", sub: "CSAT survey", variant: "end" }] },
    capabilities: [
      { icon: "MessageSquare", title: "Multi-Channel Intake", desc: "Email, phone, customer portal, web chat, social media — all tickets flow into one queue with channel-of-origin tagged." },
      { icon: "Bot", title: "AI Auto-Categorization", desc: "Inbound ticket content analyzed; category, priority, suggested resolution auto-applied. Agents start from a context-rich state." },
      { icon: "Clock", title: "SLA Timers", desc: "Every ticket has a response SLA and resolution SLA. Real-time breach risk dashboard; auto-escalation on breach." },
      { icon: "BookOpen", title: "Knowledge Base", desc: "Searchable articles, troubleshooting guides, FAQs. Customer self-service deflects 30-50% of would-be tickets." },
      { icon: "Users", title: "Customer Portal", desc: "Branded portal where customers submit tickets, track status, view history, access docs. Reduces phone-call volume significantly." },
      { icon: "Award", title: "CSAT Surveys", desc: "Post-resolution satisfaction surveys. Aggregate CSAT per agent, per team, per product. Identify training gaps." },
      { icon: "GitBranch", title: "Escalation Rules", desc: "Configurable escalation — by SLA breach, customer VIP status, complaint severity. Right escalation path every time." },
      { icon: "BarChart2", title: "Resolution Analytics", desc: "Average resolution time, first-contact resolution rate, ticket volume trends, top complaint categories. Inform product + service improvements." },
      { icon: "ScrollText", title: "Audit Trail", desc: "Every action on every ticket logged. Compliance-ready for regulated industries; auditor-self-service for any historical review." },
    ],
    integrations: [
      { module: "CRM", action: "Ticket → account history", effect: "Add to customer 360" },
      { module: "Sales", action: "Quality issue → return", effect: "Auto-trigger return workflow" },
      { module: "Quality", action: "Complaint → NCR", effect: "Quality investigation" },
      { module: "Email Hub", action: "Email-to-ticket", effect: "Inbound emails parsed" },
    ],
  },

  "marketing-automation": {
    slug: "marketing-automation", tag: "Marketing Automation", name: "Marketing",
    title: "Right message.", highlight: "Right person. Right time.",
    blurb: "Campaign management, lead nurturing, audience segmentation, email sequences, content personalization, ROI tracking. The marketing engine that runs alongside CRM.",
    photo: "https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?auto=format&fit=crop&w=1920&q=80",
    accent: "#EC4899", icon: "Megaphone",
    metrics: [{ value: "Segmented", label: "audiences" }, { value: "Nurture", label: "automation" }, { value: "Multi-touch", label: "attribution" }, { value: "ROI", label: "tracked" }],
    features: [
      { tag: "Campaigns", title: "Plan. Launch. Measure.", body: "Plan multi-channel campaigns — email, SMS, WhatsApp, print. Schedule, target audience segments, A/B test, measure response.", points: ["Multi-channel campaign builder", "Audience segmentation", "A/B testing", "Schedule + auto-send", "Per-channel response tracking", "Cost vs conversion analysis"], photo: "https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?auto=format&fit=crop&w=1200&q=80" },
      { tag: "Lead Nurturing", title: "Move leads down the funnel.", body: "Automated drip campaigns based on lead behavior — new lead → educate → qualify → hand-off. Sales gets warm leads, not cold names.", points: ["Behavior-triggered sequences", "Lead scoring + grading", "Automatic hand-off to sales when ready", "Re-engagement campaigns", "Per-stage conversion tracking", "Sales-marketing alignment"], photo: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1200&q=80", flip: true },
      { tag: "Attribution & ROI", title: "Which campaigns actually work.", body: "Multi-touch attribution — first-touch, last-touch, weighted. Per-campaign ROI calculation. Marketing dollar accountability.", points: ["Multi-touch attribution models", "Per-campaign ROI calculation", "Channel performance comparison", "Cost-per-lead, cost-per-acquisition", "Time-to-conversion tracking", "Marketing-sourced revenue reporting"], photo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80" },
    ],
    workflow: { title: "Campaign Lifecycle", nodes: [{ id: "plan", label: "Plan", sub: "audience + content", variant: "start" }, { id: "segment", label: "Segment", sub: "audience" }, { id: "launch", label: "Launch", sub: "multi-channel", variant: "active" }, { id: "track", label: "Track", sub: "engagement" }, { id: "score", label: "Score", sub: "+ qualify" }, { id: "handoff", label: "Hand-off", sub: "to sales", variant: "end" }] },
    capabilities: [
      { icon: "Megaphone", title: "Campaign Builder", desc: "Build multi-channel campaigns with email, SMS, WhatsApp, and print components. Schedule, target, A/B test from one workspace." },
      { icon: "Users", title: "Audience Segmentation", desc: "Segment by industry, size, geography, behavior, lifecycle stage. Highly-targeted campaigns outperform mass blasts." },
      { icon: "Workflow", title: "Drip Sequences", desc: "Automated email/SMS sequences triggered by lead behavior. New leads, dormant leads, post-sample leads — all on appropriate sequences." },
      { icon: "Award", title: "Lead Scoring", desc: "Score leads by demographic fit + behavior signals. Hot leads auto-routed to sales; cold leads stay in nurture." },
      { icon: "BarChart2", title: "Multi-Touch Attribution", desc: "First-touch, last-touch, time-decay, weighted models. Understand which campaigns actually drove revenue." },
      { icon: "TrendingUp", title: "ROI per Campaign", desc: "Spend vs revenue per campaign with confidence intervals. Marketing budget defended with data." },
      { icon: "RefreshCw", title: "A/B Testing", desc: "Test subject lines, content variants, send times, audience splits. Statistically-significant winners promoted automatically." },
      { icon: "Mail", title: "Email Engine", desc: "Built on Email Hub; reuses templates, deliverability, bounce handling. No separate marketing email infrastructure." },
      { icon: "Eye", title: "Engagement Tracking", desc: "Per-recipient open, click, conversion tracking. Per-segment engagement rates inform future targeting." },
    ],
    integrations: [
      { module: "CRM", action: "Qualified lead → pipeline", effect: "Auto-hand-off to sales" },
      { module: "Party", action: "Audience pull from master", effect: "Single customer database" },
      { module: "Email Hub", action: "Send infrastructure", effect: "Reuse deliverability" },
      { module: "AI", action: "Predictive lead scoring", effect: "ML model improves over time" },
    ],
  },

  "field-service": {
    slug: "field-service", tag: "Field Service Management", name: "Field Service",
    title: "Right tech.", highlight: "Right place. Right time.",
    blurb: "Technician scheduling, route optimization, on-site work orders, mobile completion, customer signature capture. For mill OEMs, service providers, and after-sales operations.",
    photo: "https://images.unsplash.com/photo-1581094271901-8022df4466f9?auto=format&fit=crop&w=1920&q=80",
    accent: "#84CC16", icon: "Wrench",
    metrics: [{ value: "Route", label: "optimized" }, { value: "Mobile", label: "completion" }, { value: "Customer", label: "sign-off" }, { value: "SLA", label: "tracked" }],
    features: [
      { tag: "Dispatch & Scheduling", title: "Right tech. Right skill.", body: "Intelligent dispatch — match technician skills + location + availability to job requirements. Route optimization for multi-stop days.", points: ["Skill-matched dispatching", "Location + availability-aware", "Multi-stop route optimization", "Real-time GPS tracking", "Customer ETA notifications", "Re-dispatch on cancellation"], photo: "https://images.unsplash.com/photo-1581094271901-8022df4466f9?auto=format&fit=crop&w=1200&q=80" },
      { tag: "On-site Execution", title: "Mobile work orders.", body: "Tech app on iOS/Android with offline-capable work order, parts inventory, customer history, photo capture, signature. Complete the job, sync when back online.", points: ["Offline-capable mobile app", "Customer + asset history at hand", "Photo evidence of work", "Customer signature capture", "Parts consumed logged", "Time-on-site tracked"], photo: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=1200&q=80", flip: true },
      { tag: "Billing & Analytics", title: "Service to invoice.", body: "Service tickets auto-create invoices with labor + parts + travel charges. Analytics on tech productivity, first-time fix rate, customer satisfaction.", points: ["Auto-invoice from service ticket", "Labor + parts + travel billing", "First-time fix rate tracking", "Per-tech productivity metrics", "CSAT per service call", "Per-customer service history"], photo: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1200&q=80" },
    ],
    workflow: { title: "Field Service Flow", nodes: [{ id: "request", label: "Service Request", sub: "from customer", variant: "start" }, { id: "dispatch", label: "Dispatch", sub: "skill + location" }, { id: "route", label: "Route", sub: "optimize", variant: "active" }, { id: "execute", label: "Execute", sub: "on-site" }, { id: "complete", label: "Complete", sub: "sign + photos" }, { id: "invoice", label: "Invoice", sub: "auto", variant: "end" }] },
    capabilities: [
      { icon: "Wrench", title: "Skill-Match Dispatch", desc: "Match technician skills, certifications, and availability to job. The right tech, the first time." },
      { icon: "MapPin", title: "Route Optimization", desc: "Multi-stop daily routes optimized for distance, traffic, priority. Save fuel + time; squeeze in more service calls per day." },
      { icon: "Smartphone", title: "Mobile Work Orders", desc: "Tech app delivers job context, history, parts list, photos. Offline-capable; works in basements and remote sites." },
      { icon: "Eye", title: "Photo Evidence", desc: "Before/after photos captured at the job site. Evidence for billing disputes, quality reviews, and warranty claims." },
      { icon: "Award", title: "Signature Capture", desc: "Customer signs on the tech's device to acknowledge service completion. Signature linked to job and invoice." },
      { icon: "Receipt", title: "Auto-Invoice", desc: "Service ticket auto-creates invoice with labor + parts + travel. Tech doesn't paperwork; office doesn't chase tech." },
      { icon: "TrendingUp", title: "First-Time Fix Rate", desc: "Track jobs completed without return visit. Coach techs on recurring callbacks; identify training gaps." },
      { icon: "Clock", title: "SLA Tracking", desc: "Service contracts have SLAs. Real-time SLA breach risk dashboard; auto-escalation on missed targets." },
      { icon: "Database", title: "Parts in Truck", desc: "Track parts inventory in each tech's truck. Restock when running low; charge consumed parts to the job." },
    ],
    integrations: [
      { module: "Maintenance", action: "Equipment WO → field tech", effect: "Maintenance teams use Field Service" },
      { module: "Sales", action: "Service contract → ticket", effect: "Auto-create on contract trigger" },
      { module: "Inventory", action: "Parts → truck stock", effect: "Stock at tech level" },
      { module: "Finance", action: "Service → invoice", effect: "Bill labor + parts + travel" },
    ],
  },

  "iot-devices": {
    slug: "iot-devices", tag: "IoT Device Management", name: "IoT",
    title: "Sensors, gateways, telemetry.", highlight: "Managed at scale.",
    blurb: "Centralized IoT device fleet management — sensor registration, firmware updates, telemetry ingestion, alerting, and the foundation for predictive maintenance and digital twin.",
    photo: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1920&q=80",
    accent: "#06B6D4", icon: "Activity",
    metrics: [{ value: "Multi-protocol", label: "OPC-UA/MQTT/REST" }, { value: "OTA", label: "firmware" }, { value: "Edge", label: "buffering" }, { value: "Time-series", label: "storage" }],
    features: [
      { tag: "Device Registration", title: "Fleet of thousands.", body: "Onboard sensors, PLCs, gateways into one fleet. Per-device identity, certificates, firmware version, location, owner. Provision in bulk; revoke on decommission.", points: ["Per-device identity + certificates", "Bulk provisioning via CSV/API", "Firmware version tracking", "Location + machine assignment", "Decommissioning workflow", "Device health dashboard"], photo: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80" },
      { tag: "Telemetry Ingestion", title: "Stream the data.", body: "Multi-protocol ingestion — OPC-UA, Modbus, MQTT, REST. Time-series storage with downsampling. Real-time stream into other modules (OEE, Maintenance, Quality).", points: ["OPC-UA / Modbus / MQTT / REST", "TimescaleDB-backed time-series", "Configurable downsampling", "Real-time stream to modules", "Historical replay for analysis", "Per-metric retention policies"], photo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80", flip: true },
      { tag: "OTA Updates", title: "Firmware. Pushed safely.", body: "Over-the-air firmware updates with staged rollout, canary deployment, automatic rollback on failure. No truck-rolls for firmware.", points: ["Staged rollout policies", "Canary deployment (5% first)", "Auto-rollback on failure signal", "Per-device + per-fleet targeting", "Update audit log", "Bandwidth-aware delivery"], photo: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80" },
    ],
    workflow: { title: "IoT Device Lifecycle", nodes: [{ id: "provision", label: "Provision", sub: "+ cert", variant: "start" }, { id: "deploy", label: "Deploy", sub: "to site" }, { id: "ingest", label: "Ingest", sub: "telemetry", variant: "active" }, { id: "monitor", label: "Monitor", sub: "health" }, { id: "update", label: "Update", sub: "firmware OTA" }, { id: "decommission", label: "Decommission", sub: "revoke", variant: "end" }] },
    capabilities: [
      { icon: "Activity", title: "Fleet Dashboard", desc: "Live status of every device — online/offline, last telemetry, firmware version, battery, signal strength. Drill into any device for full diagnostics." },
      { icon: "Server", title: "Multi-Protocol", desc: "OPC-UA for industrial automation, Modbus TCP for legacy PLCs, MQTT for modern IoT sensors, REST for cloud integrations. One platform for all." },
      { icon: "Database", title: "Time-series Storage", desc: "TimescaleDB-backed time-series with configurable retention. Downsampling preserves history without storage explosion." },
      { icon: "Workflow", title: "Stream to Modules", desc: "Live telemetry streams to OEE (Production), Maintenance (predictive), Quality (process control), and Edge (real-time decisions)." },
      { icon: "CloudUpload", title: "OTA Firmware", desc: "Push firmware updates from cloud. Staged rollout with canary deployment; auto-rollback if devices report errors." },
      { icon: "Lock", title: "Device Security", desc: "Per-device certificates (X.509). Mutual TLS. Compromised devices revoked instantly; impacted data flagged for investigation." },
      { icon: "MapPin", title: "Edge Gateway", desc: "Edge gateways aggregate local sensors, buffer during connectivity loss, run local analytics, sync when online." },
      { icon: "AlertCircle", title: "Anomaly Detection", desc: "ML watches telemetry for anomalies — sudden vibration spike, temperature drift, signal degradation. Alerts before failure." },
      { icon: "BarChart2", title: "Fleet Analytics", desc: "Fleet-wide patterns — which devices fail most, which firmware version is most stable, which sites have the worst connectivity." },
    ],
    integrations: [
      { module: "Maintenance", action: "Sensor anomaly → WO", effect: "Predictive maintenance trigger" },
      { module: "Production", action: "Live machine data → OEE", effect: "Real-time OEE calculation" },
      { module: "Stock Prep", action: "Tank levels live", effect: "Chest/flow from SCADA" },
      { module: "Quality", action: "Inline measurement", effect: "Real-time quality data" },
    ],
  },

  "digital-twin": {
    slug: "digital-twin", tag: "Digital Twin", name: "Digital Twin",
    title: "Your mill in pixels.", highlight: "Simulated. Synchronized.",
    blurb: "3D models of machines and processes, real-time sync with physical mill via IoT, simulation for what-if analysis, AR-assisted maintenance. The mill's digital mirror.",
    photo: "https://images.unsplash.com/photo-1581090464777-f3220bbe1b8b?auto=format&fit=crop&w=1920&q=80",
    accent: "#A855F7", icon: "Layers",
    metrics: [{ value: "3D", label: "models" }, { value: "Live", label: "sync" }, { value: "What-if", label: "simulation" }, { value: "AR", label: "ready" }],
    features: [
      { tag: "3D Mill Model", title: "Every machine. Modeled.", body: "3D models of paper machines, converting lines, warehouses. Click any component to see live status, last maintenance, sensor data, documentation. Visual operations dashboard.", points: ["3D models of every major asset", "Component-level click-through", "Live status overlay (red/yellow/green)", "Maintenance history per component", "Spare parts catalog linked", "Walkthrough mode for training"], photo: "https://images.unsplash.com/photo-1581090464777-f3220bbe1b8b?auto=format&fit=crop&w=1200&q=80" },
      { tag: "Simulation", title: "What if we change X?", body: "Run what-if scenarios on the digital twin — change machine speed, swap grade, modify shift pattern. Engine predicts outcomes before real change.", points: ["Speed + grade scenario sims", "Throughput prediction", "Quality outcome prediction", "Cost impact estimation", "Energy consumption forecast", "Side-by-side scenario compare"], photo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80", flip: true },
      { tag: "AR Assistance", title: "Augmented reality for maintenance.", body: "AR app overlays digital information onto physical machines — through phone camera or AR glasses. Maintenance techs see step-by-step instructions on the real equipment.", points: ["AR app for iOS / Android / glasses", "Step-by-step maintenance overlay", "Component identification via camera", "Documentation + video at point-of-need", "Remote expert assist via video", "Audit trail of AR sessions"], photo: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=1200&q=80" },
    ],
    workflow: { title: "Twin Lifecycle", nodes: [{ id: "build", label: "Build Model", sub: "3D + sensors", variant: "start" }, { id: "sync", label: "Sync", sub: "IoT live" }, { id: "visualize", label: "Visualize", sub: "current state", variant: "active" }, { id: "simulate", label: "Simulate", sub: "scenarios" }, { id: "act", label: "Act", sub: "informed decision", variant: "end" }] },
    capabilities: [
      { icon: "Layers", title: "3D Mill Model", desc: "Every major asset modeled in 3D with click-through to component-level detail. Visual operations dashboard for management walkthroughs." },
      { icon: "Activity", title: "Live IoT Sync", desc: "Sensor data from IoT module overlays the 3D model in real time. Red components are alarming; yellow are warning; green are healthy." },
      { icon: "Workflow", title: "What-if Simulation", desc: "Test changes before making them. Speed up the paper machine? Run simulation; see throughput + quality + energy impact." },
      { icon: "Brain", title: "Outcome Prediction", desc: "ML-trained on historical data predicts how scenario changes will affect throughput, quality, cost, and energy use." },
      { icon: "Eye", title: "AR Maintenance", desc: "AR overlay on physical machines through phone camera or AR glasses. Step-by-step instructions visible on the equipment itself." },
      { icon: "BookOpen", title: "Documentation Overlay", desc: "Tap any component in AR; relevant manuals, videos, drawings appear. Knowledge at the point of need." },
      { icon: "Users", title: "Remote Expert", desc: "Field tech shares AR view with remote expert who can annotate, point, and guide. Solves problems without flying in specialists." },
      { icon: "BarChart2", title: "Trend Comparison", desc: "Compare twin-predicted outcomes to actual outcomes. Model accuracy improves over time as data accumulates." },
      { icon: "FileCheck", title: "Training Mode", desc: "Use the twin for operator and maintenance training. Practice scenarios safely; build muscle memory before touching real equipment." },
    ],
    integrations: [
      { module: "IoT", action: "Sensor data → twin overlay", effect: "Real-time visualization" },
      { module: "Maintenance", action: "AR work orders", effect: "Step-by-step on equipment" },
      { module: "Production", action: "Simulation → planning", effect: "Test changes before commit" },
      { module: "AI", action: "Outcome prediction models", effect: "ML-trained scenario sim" },
    ],
  },

  sustainability: {
    slug: "sustainability", tag: "Sustainability & ESG", name: "Sustainability",
    title: "Measure. Report.", highlight: "Reduce.",
    blurb: "Carbon footprint tracking, water consumption, waste streams, energy intensity, sustainability certifications, ESG reporting per BRSR/GRI standards. The reporting layer customers + investors now expect.",
    photo: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1920&q=80",
    accent: "#16A34A", icon: "Globe",
    metrics: [{ value: "Scope 1+2+3", label: "tracked" }, { value: "BRSR", label: "+ GRI ready" }, { value: "Water", label: "+ waste" }, { value: "Per-tonne", label: "intensity" }],
    features: [
      { tag: "Footprint Tracking", title: "Every emission. Counted.", body: "Track Scope 1 (direct), Scope 2 (purchased electricity), Scope 3 (supply chain) emissions. Auto-pull from energy meters, fuel purchases, supplier data. Per-tonne intensity calculated live.", points: ["Scope 1 / 2 / 3 emissions", "Auto-feed from energy meters", "Fuel + chemical emission factors", "Supply chain emissions (Scope 3)", "Per-tonne carbon intensity", "Year-over-year comparison"], photo: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1200&q=80" },
      { tag: "Water & Waste", title: "Beyond carbon.", body: "Water consumption (intake + discharge), wastewater quality, solid waste streams, hazardous waste. Per-grade water intensity; effluent quality monitoring.", points: ["Water intake + discharge metering", "Wastewater quality (BOD/COD/TSS)", "Solid waste classification + disposal", "Hazardous waste tracking", "Per-tonne water intensity", "Recycled water percentage"], photo: "https://images.unsplash.com/photo-1581094271901-8022df4466f9?auto=format&fit=crop&w=1200&q=80", flip: true },
      { tag: "ESG Reporting", title: "Auditor-ready.", body: "Pre-built reporting templates for BRSR (Business Responsibility & Sustainability Report — India), GRI Standards, SASB, FSC, PEFC. Evidence-backed; auditor self-service.", points: ["BRSR Section A/B/C", "GRI Universal + Topic Standards", "SASB sector-specific", "FSC chain-of-custody reporting", "PEFC certification reports", "Customer ESG questionnaire responses"], photo: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80" },
    ],
    workflow: { title: "ESG Data Flow", nodes: [{ id: "collect", label: "Collect", sub: "meters + records", variant: "start" }, { id: "calc", label: "Calculate", sub: "emission factors" }, { id: "aggregate", label: "Aggregate", sub: "by scope" }, { id: "report", label: "Report", sub: "BRSR / GRI", variant: "active" }, { id: "audit", label: "Audit", sub: "evidence trail" }, { id: "publish", label: "Publish", sub: "stakeholders", variant: "end" }] },
    capabilities: [
      { icon: "Globe", title: "Scope 1/2/3 Emissions", desc: "Complete carbon accounting — direct emissions, purchased electricity, supply chain. Pre-loaded emission factors per fuel and electricity source." },
      { icon: "Activity", title: "Live Energy Meters", desc: "Energy data pulled live from sub-meters. Per-machine and per-grade kWh intensity tracked; outliers investigated." },
      { icon: "Database", title: "Water Tracking", desc: "Intake from sources, discharge to outfalls, recycling rates. Per-tonne water intensity benchmarked against industry." },
      { icon: "AlertCircle", title: "Waste Streams", desc: "Solid waste by category, hazardous waste with disposal manifests, recycling rates. Compliance with state pollution control boards." },
      { icon: "FileCheck", title: "BRSR Reporting", desc: "Pre-built Section A/B/C templates for India's mandatory BRSR. Auto-populate from operational data; evidence linked." },
      { icon: "Award", title: "Multi-Standard Support", desc: "GRI Universal + Topic Standards, SASB sector-specific, TCFD climate disclosures. One data set, multiple report formats." },
      { icon: "ScrollText", title: "Audit Trail", desc: "Every number traceable to source — meter reading, purchase invoice, lab test result. Auditor-ready evidence." },
      { icon: "TrendingDown", title: "Reduction Targets", desc: "Set science-based targets per scope. Live progress dashboard; gap-to-target visualized; intervention recommendations." },
      { icon: "Users", title: "Customer ESG", desc: "Respond to customer ESG questionnaires from a pre-validated knowledge base. Same answer every time; consistent positioning." },
    ],
    integrations: [
      { module: "IoT", action: "Meter data → emissions", effect: "Real-time intensity" },
      { module: "Procurement", action: "Supplier data → Scope 3", effect: "Supply chain emissions" },
      { module: "Production", action: "Per-grade footprint", effect: "Grade-level intensity" },
      { module: "Audit", action: "ESG evidence trail", effect: "Auditor self-service" },
    ],
  },

  "edge-computing": {
    slug: "edge-computing", tag: "Edge Computing", name: "Edge",
    title: "Decisions at the edge.", highlight: "Latency. Resilience.",
    blurb: "Edge gateways that run analytics locally on the shop floor — predictive maintenance models, quality outliers, control loops. Offline-capable; sync with cloud when connected.",
    photo: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1920&q=80",
    accent: "#0891B2", icon: "Cpu" as string,
    metrics: [{ value: "Edge AI", label: "inference" }, { value: "Offline", label: "capable" }, { value: "Low", label: "latency" }, { value: "Buffered", label: "sync" }],
    features: [
      { tag: "Edge Gateways", title: "Compute at the shop floor.", body: "Industrial edge gateways run analytics close to the sensors — sub-millisecond inference, no cloud round-trip. Critical for control loops and real-time alerts.", points: ["Industrial-grade edge hardware", "Sub-millisecond ML inference", "Local data buffering during outages", "Auto-sync when connectivity returns", "Hot-swap failover support", "Remote diagnostics + updates"], photo: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80" },
      { tag: "Edge ML Inference", title: "AI models. Local.", body: "Deploy ML models to edge for predictive maintenance, quality outlier detection, energy optimization. Cloud trains; edge infers; data flows back for retraining.", points: ["TensorFlow Lite / ONNX models", "OTA model updates", "Per-device model versioning", "Inference monitoring + drift detection", "Cloud-to-edge model deployment", "Per-model accuracy tracking"], photo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80", flip: true },
      { tag: "Offline Resilience", title: "Mill keeps running.", body: "When internet is down, edge keeps the mill running — local data, local rules, local decisions. Buffered data syncs when connectivity returns.", points: ["Hours-to-days of local buffering", "Local rule execution offline", "Cached master data", "Conflict resolution on resync", "Per-edge data quotas", "Bandwidth-aware sync scheduling"], photo: "https://images.unsplash.com/photo-1581094271901-8022df4466f9?auto=format&fit=crop&w=1200&q=80" },
    ],
    workflow: { title: "Edge Compute Flow", nodes: [{ id: "sensor", label: "Sensor", sub: "raw data", variant: "start" }, { id: "edge", label: "Edge Gateway", sub: "buffer + infer", variant: "active" }, { id: "decide", label: "Decide", sub: "local rule" }, { id: "act", label: "Act", sub: "alert + control" }, { id: "sync", label: "Sync", sub: "to cloud" }, { id: "retrain", label: "Retrain", sub: "model update", variant: "end" }] },
    capabilities: [
      { icon: "Server", title: "Edge Gateway Hardware", desc: "Industrial gateways with ruggedized enclosures, redundant power, multi-network connectivity. Designed for harsh shop floor environments." },
      { icon: "Brain", title: "Edge ML Inference", desc: "Run ML models at the edge — predictive maintenance, quality anomaly, energy optimization. Sub-millisecond decisions; no cloud round-trip." },
      { icon: "Database", title: "Local Buffering", desc: "Hours to days of telemetry buffered locally. No data loss during connectivity outages; sync resumes automatically." },
      { icon: "RefreshCw", title: "Model Lifecycle", desc: "Train models in cloud, deploy to edge via OTA. Monitor inference accuracy; retrain when drift detected." },
      { icon: "Workflow", title: "Local Rule Engine", desc: "Configurable rules execute locally — 'if temp > X and pressure > Y, alert operator and shut motor'. No cloud dependency for safety-critical decisions." },
      { icon: "CloudUpload", title: "Smart Sync", desc: "Bandwidth-aware sync scheduling — full sync on Wi-Fi, summary-only on cellular, queue when offline. No bandwidth burns." },
      { icon: "Lock", title: "Edge Security", desc: "Each edge has unique identity + certificate. Encrypted at-rest storage; revocable on compromise." },
      { icon: "Eye", title: "Remote Diagnostics", desc: "Cloud dashboard for every edge gateway — health, latency, model accuracy, storage, errors. Triage without truck-rolls." },
      { icon: "AlertCircle", title: "Anomaly Detection", desc: "Edges detect local anomalies before they propagate. Faster response than cloud-only architectures." },
    ],
    integrations: [
      { module: "IoT", action: "Sensor data → edge", effect: "Local ingestion + inference" },
      { module: "Maintenance", action: "Edge anomaly → WO", effect: "Predictive trigger" },
      { module: "Production", action: "Quality outlier → halt", effect: "Real-time control" },
      { module: "AI", action: "Cloud-trained models → edge", effect: "OTA model deployment" },
    ],
  },

  rpa: {
    slug: "rpa", tag: "RPA / Bot Orchestration", name: "RPA",
    title: "Bots that work.", highlight: "While humans sleep.",
    blurb: "Robotic Process Automation — software bots that perform repetitive tasks across legacy systems, web portals, and Excel. OCR-driven data extraction, screen scraping, form filling, scheduled batch operations.",
    photo: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=1920&q=80",
    accent: "#FB923C", icon: "Bot",
    metrics: [{ value: "Attended", label: "+ unattended" }, { value: "OCR", label: "pipelines" }, { value: "Audit", label: "every step" }, { value: "ROI", label: "tracked" }],
    features: [
      { tag: "Bot Library", title: "Pre-built. Customizable.", body: "Library of pre-built bots — GST portal reconciliation, bank statement parsing, vendor invoice OCR, e-Way bill generation. Deploy in days; customize without code.", points: ["GST portal scrapers", "Bank statement parsers", "Vendor invoice OCR", "e-Way bill generators", "Custom bot builder", "Per-bot version control"], photo: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?auto=format&fit=crop&w=1200&q=80" },
      { tag: "Attended + Unattended", title: "Human-in-loop. Or not.", body: "Attended bots run alongside humans, automating parts of workflows. Unattended bots run on schedules, independent of users. Mix and match per process.", points: ["Attended (user-initiated)", "Unattended (scheduled)", "Hybrid (human-approval gates)", "Exception handling + retry", "Concurrent bot pool", "Bot license management"], photo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80", flip: true },
      { tag: "OCR Pipelines", title: "Paper to data. Automated.", body: "OCR pipelines extract structured data from scanned invoices, POs, certificates, lab reports. Confidence scoring; human review for low-confidence items; auto-attach to transactions.", points: ["Multi-language OCR (EN/HI/TA)", "Layout-aware extraction", "Confidence scoring per field", "Human review queue for low-confidence", "Auto-attach to matching transaction", "Continuous accuracy improvement"], photo: "https://images.unsplash.com/photo-1606857521015-7f9fcf423740?auto=format&fit=crop&w=1200&q=80" },
    ],
    workflow: { title: "Bot Lifecycle", nodes: [{ id: "build", label: "Build", sub: "designer", variant: "start" }, { id: "test", label: "Test", sub: "sandbox" }, { id: "deploy", label: "Deploy", sub: "+ schedule" }, { id: "run", label: "Run", sub: "attended/unattended", variant: "active" }, { id: "monitor", label: "Monitor", sub: "SLA + audit" }, { id: "improve", label: "Improve", sub: "iterate", variant: "end" }] },
    capabilities: [
      { icon: "Bot", title: "Bot Library", desc: "Pre-built bots for common paper-mill workflows — GST scraping, bank parsing, vendor invoice OCR, statutory portal interaction. Deploy in days." },
      { icon: "Workflow", title: "Visual Bot Designer", desc: "Drag-drop designer for custom bots. Record-and-replay, screen scraping, API calls, OCR — all visual, no code required." },
      { icon: "Eye", title: "OCR Engine", desc: "Multi-language OCR with layout awareness. Vendor invoices, POs, certificates, lab reports — extracted with confidence scores." },
      { icon: "Clock", title: "Scheduled Bots", desc: "Unattended bots run on cron schedules — nightly bank reconciliation, weekly statutory portal sync, monthly customer statement parsing." },
      { icon: "Users", title: "Attended Bots", desc: "User-triggered bots automate steps within a user's workflow. 'Fetch this customer's outstanding from 5 systems and show me' becomes one click." },
      { icon: "AlertCircle", title: "Exception Handling", desc: "Bots gracefully handle exceptions — UI changes, network errors, unexpected data. Failures notified to bot owner with diagnostic context." },
      { icon: "ScrollText", title: "Full Audit Trail", desc: "Every bot action logged — what URL was visited, what data was extracted, what change was made. Auditor-ready for regulated processes." },
      { icon: "TrendingUp", title: "ROI Tracking", desc: "Per-bot ROI calculation — time saved × hourly cost vs bot license + maintenance. Identify high-ROI bots to scale; retire low-ROI ones." },
      { icon: "Lock", title: "Bot Security", desc: "Bots run with their own credentials, scoped permissions. No shared logins; no permission escalation; revoke instantly on compromise." },
    ],
    integrations: [
      { module: "Automations", action: "Workflow → bot trigger", effect: "Bots as workflow steps" },
      { module: "Documents", action: "OCR results → docs", effect: "Auto-classify + tag" },
      { module: "Finance", action: "Bank statement bot", effect: "Auto-reconciliation" },
      { module: "Audit", action: "Bot actions → log", effect: "Compliance evidence" },
    ],
  },

  voice: {
    slug: "voice", tag: "Voice Interface", name: "Voice",
    title: "Hands busy.", highlight: "Voice ready.",
    blurb: "Speech-to-text and voice commands for shop floor workflows — log production entries, mark quality results, capture breakdown observations, request approvals. When hands are gloved and screens are far.",
    photo: "https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=1920&q=80",
    accent: "#7C3AED", icon: "MessageSquare",
    metrics: [{ value: "Multi-lang", label: "EN/HI/TA" }, { value: "On-device", label: "STT" }, { value: "Wake-word", label: "+ push-to-talk" }, { value: "Offline", label: "capable" }],
    features: [
      { tag: "Voice Commands", title: "Say it. Done.", body: "Voice commands for shop floor entries — 'Log 240 kg broke, wet end, machine 2' becomes a complete record. No phone juggling; no glove removal.", points: ["Natural language commands", "Per-module command vocabularies", "Context-aware (current shift, current machine)", "Push-to-talk + wake-word modes", "Confirmation prompts for critical actions", "Voice-to-text fallback for free-form"], photo: "https://images.unsplash.com/photo-1606761568499-6d2451b23c66?auto=format&fit=crop&w=1200&q=80" },
      { tag: "Multi-Language", title: "English. हिंदी. தமிழ்.", body: "Native support for English, Hindi, Tamil. Mixed-language conversation supported. Per-user preference; auto-detection.", points: ["English / Hindi / Tamil supported", "Mixed-language conversation", "Per-user preference setting", "Per-shift language profiles", "Industry-specific vocabulary tuning", "Continuous accuracy improvement"], photo: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?auto=format&fit=crop&w=1200&q=80", flip: true },
      { tag: "On-Device Processing", title: "No cloud. No latency.", body: "Speech-to-text runs on-device for shop floor workflows — no cloud round-trip, no internet required, no audio leaves the device. Privacy + performance.", points: ["On-device STT models", "Sub-second response time", "No internet required", "Audio never leaves device", "Per-language model optimization", "Battery-efficient inference"], photo: "https://images.unsplash.com/photo-1556656793-08538906a9f8?auto=format&fit=crop&w=1200&q=80" },
    ],
    workflow: { title: "Voice Command Flow", nodes: [{ id: "wake", label: "Wake", sub: "button/word", variant: "start" }, { id: "listen", label: "Listen", sub: "audio capture" }, { id: "stt", label: "STT", sub: "on-device", variant: "active" }, { id: "parse", label: "Parse", sub: "intent + entities" }, { id: "confirm", label: "Confirm", sub: "if critical" }, { id: "execute", label: "Execute", sub: "+ audit log", variant: "end" }] },
    capabilities: [
      { icon: "MessageSquare", title: "Natural Commands", desc: "'Log 240 kg broke from wet end' just works. The engine parses intent and entities; no rigid command syntax to memorize." },
      { icon: "Globe", title: "Multi-Lingual", desc: "English, Hindi, Tamil supported natively. Operators speak their language; system understands. Mixed-language sentences fine." },
      { icon: "Smartphone", title: "On-Device STT", desc: "Speech-to-text runs locally on the mobile or wearable. No latency, no internet needed, no audio sent to cloud." },
      { icon: "Lock", title: "Privacy First", desc: "Audio never leaves the device by default. Compliance with HR conversations, sensitive data handling, plant security." },
      { icon: "AlertCircle", title: "Confirmation Gates", desc: "Critical actions (approval, payment release) require voice confirmation. 'Confirm sending ₹4.2L to vendor X' before execution." },
      { icon: "Eye", title: "Context Awareness", desc: "Knows which shift, which machine, which user is speaking. 'Log production' fills the right context automatically." },
      { icon: "Workflow", title: "Module Integration", desc: "Voice connects to every module — production entries, attendance, quality observations, approvals, breakdown logs." },
      { icon: "Brain", title: "Industry Vocabulary", desc: "Tuned on paper-mill terminology — 'kraft', 'GSM', 'broke', 'reel', 'pulper', 'calender'. Industry-specific accuracy." },
      { icon: "ScrollText", title: "Voice Audit Log", desc: "Every voice command logged with timestamp, user, transcript, action taken. Auditable like every other action." },
    ],
    integrations: [
      { module: "Production", action: "Voice → production entry", effect: "Hands-free shop floor" },
      { module: "Quality", action: "Voice → QC result", effect: "Quick observation capture" },
      { module: "Maintenance", action: "Voice → breakdown log", effect: "Field tech voice notes" },
      { module: "Approvals", action: "Voice → approval", effect: "On-the-go decisions" },
    ],
  },

  "document-intelligence": {
    slug: "document-intelligence", tag: "Document Intelligence", name: "Doc Intel",
    title: "Paper to structured data.", highlight: "Automatically.",
    blurb: "OCR + AI entity extraction + semantic search across every document in the system. Inbound invoices, supplier docs, contracts, certificates — all become structured, searchable, actionable data.",
    photo: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1920&q=80",
    accent: "#0EA5E9", icon: "Eye",
    metrics: [{ value: "OCR", label: "multi-lang" }, { value: "Entity", label: "extraction" }, { value: "Semantic", label: "search" }, { value: "Auto-link", label: "to txn" }],
    features: [
      { tag: "Smart OCR", title: "Read like a human.", body: "OCR that understands document layouts — tables, multi-column, handwritten notes. Per-field confidence scoring; human review queue for uncertain extractions.", points: ["Layout-aware OCR (tables, columns)", "Handwriting recognition", "Per-field confidence scoring", "Multi-language support", "Stamp + signature detection", "Continuous accuracy improvement"], photo: "https://images.unsplash.com/photo-1606857521015-7f9fcf423740?auto=format&fit=crop&w=1200&q=80" },
      { tag: "Entity Extraction", title: "Find the meaningful bits.", body: "AI identifies entities — vendor name, GSTIN, invoice number, line items, amounts, dates. Maps to canonical entities in the system; flags new entities for review.", points: ["Named entity recognition", "Domain-specific entity types", "Canonical entity matching", "Confidence per entity", "New entity flagging", "Bulk-extract from doc batches"], photo: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&w=1200&q=80", flip: true },
      { tag: "Semantic Search", title: "Find by meaning. Not just text.", body: "Search 'contracts with payment terms above 60 days' across thousands of contracts. Vector embeddings + semantic matching surface the right docs even with different wording.", points: ["Vector embedding-based search", "Cross-document semantic queries", "Natural language search", "Filter by date, type, owner", "Search across modules", "Re-ranking by relevance"], photo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80" },
    ],
    workflow: { title: "Doc Intel Flow", nodes: [{ id: "upload", label: "Upload", sub: "any format", variant: "start" }, { id: "ocr", label: "OCR", sub: "+ layout" }, { id: "extract", label: "Extract", sub: "entities", variant: "active" }, { id: "match", label: "Match", sub: "canonical" }, { id: "index", label: "Index", sub: "semantic" }, { id: "use", label: "Use", sub: "search + auto-link", variant: "end" }] },
    capabilities: [
      { icon: "Eye", title: "Layout-Aware OCR", desc: "Tables, multi-column layouts, mixed fonts, handwriting. Extracts as structured data with positional context preserved." },
      { icon: "Brain", title: "Entity Recognition", desc: "AI identifies vendors, customers, products, amounts, dates, GSTINs, invoice numbers. Maps to canonical entities in your system." },
      { icon: "Search", title: "Semantic Search", desc: "Vector embedding-based search finds documents by meaning, not just keyword. 'Contracts ending in next 60 days' actually works." },
      { icon: "GitMerge", title: "Auto-Match to Txn", desc: "Inbound invoice OCR auto-matches to open PO. Receipt OCR matches to invoice. Confidence scores guide automatic vs review-required paths." },
      { icon: "AlertCircle", title: "Review Queue", desc: "Low-confidence extractions queue for human review. Reviewers see original doc + extracted data; correct or accept in one click." },
      { icon: "RefreshCw", title: "Continuous Learning", desc: "Every correction improves the model. Vendor-specific quirks learned over time; accuracy goes up as document volume grows." },
      { icon: "Database", title: "Searchable Archive", desc: "Every uploaded doc becomes searchable — by content, metadata, entities, semantic similarity. Auditor-ready knowledge base." },
      { icon: "Lock", title: "Privacy Preserving", desc: "Per-doc access controls inherit from source module. Sensitive contracts only visible to authorized users — search results respect permissions." },
      { icon: "Globe", title: "Multi-Lingual", desc: "OCR and entity extraction work across English, Hindi, Tamil. Cross-language search retrieves Hindi docs from English queries." },
    ],
    integrations: [
      { module: "Documents", action: "Doc upload → OCR + index", effect: "Every doc searchable" },
      { module: "Procurement", action: "Vendor invoice OCR → 3-way match", effect: "Auto-match to PO" },
      { module: "Party", action: "Cert upload → entity extract", effect: "Auto-populate validity dates" },
      { module: "RPA", action: "OCR pipeline trigger", effect: "Batch doc processing" },
    ],
  },

  "engineering-change": {
    slug: "engineering-change", tag: "Engineering Change Management", name: "ECM",
    title: "Change. Controlled.", highlight: "Impact. Analyzed.",
    blurb: "Engineering Change Request workflow with impact analysis across BOMs, recipes, customer specs, in-flight production. Approval routing, version control, effective dating. The right way to change product definitions.",
    photo: "https://images.unsplash.com/photo-1453928582365-b6ad33cbcf64?auto=format&fit=crop&w=1920&q=80",
    accent: "#F472B6", icon: "GitBranch",
    metrics: [{ value: "ECR", label: "workflow" }, { value: "Impact", label: "analyzed" }, { value: "Multi-tier", label: "approval" }, { value: "Effective", label: "dating" }],
    features: [
      { tag: "ECR Workflow", title: "Request. Review. Implement.", body: "Engineering Change Requests flow from initiation through impact analysis, technical review, business approval, implementation, and verification. Every step audited; no shortcuts.", points: ["Initiation by any authorized user", "Mandatory impact analysis", "Technical + business review", "Multi-tier approval routing", "Implementation tracking", "Verification of effectiveness"], photo: "https://images.unsplash.com/photo-1453928582365-b6ad33cbcf64?auto=format&fit=crop&w=1200&q=80" },
      { tag: "Impact Analysis", title: "What breaks if we change this?", body: "Automated impact analysis — which BOMs reference this material, which products use this recipe, which customer specs are affected, which in-flight WOs need updates.", points: ["Forward impact tree", "Backward dependency tree", "Cost impact estimation", "Customer notification list", "In-flight transaction list", "Risk classification (high/med/low)"], photo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=80", flip: true },
      { tag: "Effective Dating", title: "When does the change kick in?", body: "Every change has an effective date range. In-flight transactions keep their original version; future transactions get the updated version. No retroactive surprises.", points: ["Effective date per change", "Per-record version snapshots", "In-flight transaction preservation", "Future-dated change preview", "Rollback if change fails", "Audit log of every version"], photo: "https://images.unsplash.com/photo-1606857521015-7f9fcf423740?auto=format&fit=crop&w=1200&q=80" },
    ],
    workflow: { title: "ECR Lifecycle", nodes: [{ id: "request", label: "Request", sub: "ECR initiated", variant: "start" }, { id: "impact", label: "Impact", sub: "analysis" }, { id: "tech", label: "Tech Review", sub: "+ feasibility" }, { id: "biz", label: "Biz Approval", sub: "multi-tier", variant: "active" }, { id: "implement", label: "Implement", sub: "effective date" }, { id: "verify", label: "Verify", sub: "effectiveness", variant: "end" }] },
    capabilities: [
      { icon: "GitBranch", title: "ECR Workflow", desc: "Structured Engineering Change Request workflow from request to verification. Every change goes through the right gates; no quiet edits to master data." },
      { icon: "Search", title: "Impact Analysis", desc: "Auto-trace which BOMs, recipes, products, customer specs, and in-flight transactions are affected by a proposed change. See the blast radius before approving." },
      { icon: "Calendar", title: "Effective Dating", desc: "Changes don't happen instantly — they have effective from/to dates. In-flight WOs see old version; new WOs see new version. Cleanly handles transitions." },
      { icon: "Users", title: "Multi-Tier Approval", desc: "Technical review by engineering, business approval by sales/operations, customer notification if specs change. Configurable per change type." },
      { icon: "AlertTriangle", title: "Risk Classification", desc: "Auto-classify changes by risk — material change to a flagship grade is high-risk; cosmetic packaging change is low. Approval rigor matches risk." },
      { icon: "RefreshCw", title: "Rollback Support", desc: "If a change degrades quality or cost, rollback to the previous version is one click. Affected WOs auto-update." },
      { icon: "FileText", title: "Change Documentation", desc: "Every change requires reason, supporting documents, validation evidence. ISO 9001 / IATF 16949 audit-ready." },
      { icon: "ScrollText", title: "Audit Trail", desc: "Every ECR tracked from initiation to verification — who proposed, who approved, when implemented, whether effective. Complete history." },
      { icon: "Bell", title: "Customer Notification", desc: "When customer-spec-affecting changes are approved, customers in scope are auto-notified. No surprises in their incoming shipments." },
    ],
    integrations: [
      { module: "Product Catalog", action: "Change → product update", effect: "Versioned with audit" },
      { module: "Recipe Dev", action: "Recipe change → ECR", effect: "Trial + commercial flow" },
      { module: "Production", action: "Effective date → WO version", effect: "In-flight WOs preserved" },
      { module: "Sales", action: "Customer spec change → notify", effect: "Customer auto-informed" },
    ],
  },
};

export const EXTRA_SLUGS = Object.keys(EXTRA_MODULES);
